const fs=require('fs'),path=require('path'),os=require('os'),{spawn}=require('child_process');
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'come-sayula-restart-')),dbFile=path.join(dataDir,'come_sayula.db'),port=3202,base=`http://127.0.0.1:${port}`;
const env={...process.env,NODE_ENV:'production',OPENAI_API_KEY:'',DATA_DIR:dataDir,DB_FILE:dbFile,PORT:String(port),ADMIN_EMAIL:'restart-admin@test.local',ADMIN_PASSWORD:'Reinicio-Pruebas-2026',JWT_SECRET:'restart-test-secret-that-is-longer-than-forty-eight-characters',DISABLE_AUTOMATIC_BACKUP:'1'};
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const api=async(url,options={})=>{const response=await fetch(base+url,{method:options.method||'GET',headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.token?{Authorization:'Bearer '+options.token}:{})},body:options.body?JSON.stringify(options.body):undefined});let data={};try{data=await response.json()}catch{}return {status:response.status,data,headers:response.headers};};
async function start(){const child=spawn(process.execPath,['server.js'],{cwd:__dirname,env,stdio:['ignore','ignore','pipe']});let error='';child.stderr.on('data',chunk=>error+=chunk);for(let attempt=0;attempt<40;attempt++){await wait(150);try{if((await api('/api/health')).status===200)return child}catch{}if(child.exitCode!==null)break}child.kill();throw new Error('El servidor no inició: '+error.trim());}
const stop=child=>new Promise(resolve=>{if(child.exitCode!==null)return resolve();child.once('close',resolve);child.kill();setTimeout(()=>{if(child.exitCode===null)child.kill('SIGKILL')},1000);});
async function run(){let child;try{child=await start();const created=await api('/api/auth/register',{method:'POST',body:{name:'Cliente Persistente',email:'persistente@test.local',phone:'3410000000',password:'Persistencia-12',role:'customer',termsAccepted:true}});if(created.status!==201)throw new Error('No se pudo preparar la cuenta persistente');const adminBefore=await api('/api/auth/login',{method:'POST',body:{email:'restart-admin@test.local',password:'Reinicio-Pruebas-2026',role:'admin'}});if(adminBefore.status!==200)throw new Error('No se pudo preparar la cuenta administrativa');const camaradas=await api('/api/admin/users',{token:adminBefore.data.token,method:'POST',body:{name:'Los Camaradas',email:'camaradas@test.local',phone:'3410000000',password:'Camaradas-Prueba-2026',role:'restaurant'}});if(camaradas.status!==201)throw new Error('No se pudo preparar Los Camaradas');const approved=await api('/api/admin/users/'+camaradas.data.id+'/status',{token:adminBefore.data.token,method:'PATCH',body:{status:'approved'}});if(approved.status!==200)throw new Error('No se pudo aprobar Los Camaradas');await stop(child);child=null;const restarted=await start();child=restarted;const customerLogin=await api('/api/auth/login',{method:'POST',body:{email:'persistente@test.local',password:'Persistencia-12',role:'customer'}}),adminLogin=await api('/api/auth/login',{method:'POST',body:{email:'restart-admin@test.local',password:'Reinicio-Pruebas-2026',role:'admin'}}),restaurantLogin=await api('/api/auth/login',{method:'POST',body:{email:'camaradas@test.local',password:'Camaradas-Prueba-2026',role:'restaurant'}}),restaurantPanel=await api('/api/restaurant/me',{token:restaurantLogin.data.token}),health=await api('/api/health');if(customerLogin.status!==200||adminLogin.status!==200||restaurantLogin.status!==200||restaurantPanel.data.name!=='Los Camaradas'||health.status!==200||health.data.database!=='ok')throw new Error('Las cuentas o el restaurante no sobrevivieron al reinicio');if(!health.headers.get('strict-transport-security')||!health.headers.get('cache-control')?.includes('no-store'))throw new Error('Faltan encabezados de producción');console.log('✓ Reinicio conserva cliente, administrador y restaurante Los Camaradas');console.log('✓ Producción aplica encabezados seguros');}finally{if(child)await stop(child);fs.rmSync(dataDir,{recursive:true,force:true});}}
run().catch(error=>{console.error('PRUEBA DE REINICIO FALLIDA:',error.message);process.exitCode=1;});
