const fs=require('fs'),path=require('path'),os=require('os'),{spawn}=require('child_process');
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'come-sayula-restart-')),dbFile=path.join(dataDir,'come_sayula.db'),port=3202,base=`http://127.0.0.1:${port}`;
const env={...process.env,OPENAI_API_KEY:'',DATA_DIR:dataDir,DB_FILE:dbFile,PORT:String(port),ADMIN_EMAIL:'restart-admin@test.local',ADMIN_PASSWORD:'Reinicio-Pruebas-2026',DISABLE_AUTOMATIC_BACKUP:'1'};
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const api=async(url,options={})=>{const response=await fetch(base+url,{method:options.method||'GET',headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.token?{Authorization:'Bearer '+options.token}:{})},body:options.body?JSON.stringify(options.body):undefined});let data={};try{data=await response.json()}catch{}return {status:response.status,data};};
async function start(){const child=spawn(process.execPath,['server.js'],{cwd:__dirname,env,stdio:['ignore','ignore','pipe']});let error='';child.stderr.on('data',chunk=>error+=chunk);for(let attempt=0;attempt<40;attempt++){await wait(150);try{if((await api('/api/health')).status===200)return child}catch{}if(child.exitCode!==null)break}child.kill();throw new Error('El servidor no inició: '+error.trim());}
const stop=child=>new Promise(resolve=>{if(child.exitCode!==null)return resolve();child.once('close',resolve);child.kill();setTimeout(()=>{if(child.exitCode===null)child.kill('SIGKILL')},1000);});
async function run(){let child;try{child=await start();const created=await api('/api/auth/register',{method:'POST',body:{name:'Cliente Persistente',email:'persistente@test.local',phone:'3410000000',password:'Persistencia-12',role:'customer',termsAccepted:true}});if(created.status!==201)throw new Error('No se pudo preparar la cuenta persistente');await stop(child);child=null;const restarted=await start();child=restarted;const login=await api('/api/auth/login',{method:'POST',body:{email:'persistente@test.local',password:'Persistencia-12',role:'customer'}}),health=await api('/api/health');if(login.status!==200||health.status!==200||health.data.database!=='ok')throw new Error('El estado no sobrevivió al reinicio');console.log('✓ Reinicio conserva la base de datos, las cuentas y la salud del servidor');}finally{if(child)await stop(child);fs.rmSync(dataDir,{recursive:true,force:true});}}
run().catch(error=>{console.error('PRUEBA DE REINICIO FALLIDA:',error.message);process.exitCode=1;});
