const fs=require('fs'),path=require('path'),os=require('os'),{spawn}=require('child_process'),crypto=require('crypto');
const root=__dirname,dbFile=path.join(os.tmpdir(),'test-come-sayula.db'),port=3199,base=`http://127.0.0.1:${port}`;
for(const suffix of ['', '-wal','-shm'])try{fs.unlinkSync(dbFile+suffix)}catch(e){}
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,OPENAI_API_KEY:'',DATA_DIR:os.tmpdir(),DB_FILE:dbFile,PORT:String(port),ADMIN_EMAIL:'admin@test.local',ADMIN_PASSWORD:'Admin-Pruebas-2026',DISABLE_AUTOMATIC_BACKUP:'1'},stdio:['ignore','pipe','pipe']});
let serverError='';child.stderr.on('data',chunk=>serverError+=chunk.toString());
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function api(url,{token,method='GET',body}={}){const response=await fetch(base+url,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});let data={};try{data=await response.json()}catch(e){}return {status:response.status,data};}
function ok(condition,message){if(!condition)throw new Error(message);console.log('✓ '+message)}
async function login(email,password,role){const r=await api('/api/auth/login',{method:'POST',body:{email,password,role}});ok(r.status===200,'inicio de sesión '+role);return r.data.token}
async function run(){
  for(let i=0;i<30;i++){await wait(150);try{if((await api('/api/health')).status===200)break}catch(e){}if(i===29)throw new Error('El servidor de prueba no inició: '+serverError.trim())}
  const denied=await api('/api/auth/register',{method:'POST',body:{name:'Intruso',email:'staff-public@test.local',password:'Contrasena12',role:'delivery',termsAccepted:true}});ok(denied.status===403,'registro público bloquea roles operativos');
  const customer=await api('/api/auth/register',{method:'POST',body:{name:'Cliente Prueba',email:'cliente@test.local',phone:'3410000000',password:'Cliente-Prueba-12',role:'customer',termsAccepted:true}});ok(customer.status===201,'registro público permite clientes con consentimiento');
  const admin=await login('admin@test.local','Admin-Pruebas-2026','admin');
  const aiStatus=await api('/api/ai/status',{token:admin});ok(aiStatus.status===200&&aiStatus.data.enabled===false,'asistente informa cuando falta configuración');
  const aiUnavailable=await api('/api/ai/chat',{token:admin,method:'POST',body:{message:'Resume la operación'}});ok(aiUnavailable.status===503,'asistente falla de forma segura sin clave');
  const pushKey=await api('/api/push/public-key',{token:admin});ok(pushKey.status===200&&typeof pushKey.data.publicKey==='string'&&pushKey.data.publicKey.length>40,'servidor prepara notificaciones móviles cifradas');
  for(const user of [{name:'Restaurante Prueba',email:'rest@test.local',phone:'3411',password:'Restaurante-12',role:'restaurant'},{name:'Repartidor Uno',email:'rep1@test.local',password:'Repartidor-uno-12',role:'delivery'},{name:'Repartidor Dos',email:'rep2@test.local',password:'Repartidor-dos-12',role:'delivery'}]){const c=await api('/api/admin/users',{token:admin,method:'POST',body:user});ok(c.status===201,'administrador crea '+user.role);const a=await api('/api/admin/users/'+c.data.id+'/status',{token:admin,method:'PATCH',body:{status:'approved'}});ok(a.status===200,'administrador aprueba '+user.email)}
  const restaurant=await login('rest@test.local','Restaurante-12','restaurant'),d1=await login('rep1@test.local','Repartidor-uno-12','delivery'),d2=await login('rep2@test.local','Repartidor-dos-12','delivery');
  const employeeCreated=await api('/api/restaurant/employees',{token:restaurant,method:'POST',body:{name:'Empleado Pedidos',email:'empleado@test.local',phone:'3412',password:'Empleado-Seguro-12',canManageOrders:true,canManageProducts:false,canViewFinance:false}});ok(employeeCreated.status===201,'dueño crea acceso individual para empleado');
  const employee=await login('empleado@test.local','Empleado-Seguro-12','restaurant');
  const employeePanel=await api('/api/restaurant/me',{token:employee});ok(employeePanel.status===200&&employeePanel.data.access?.isOwner===false&&employeePanel.data.access?.canManageOrders===true,'empleado entra al negocio con permisos propios');
  const employeeFinance=await api('/api/restaurant/settlement',{token:employee});ok(employeeFinance.status===403,'empleado sin permiso no puede ver cortes');
  const employeeProduct=await api('/api/restaurant/products',{token:employee,method:'POST',body:{name:'No autorizado',price:20}});ok(employeeProduct.status===403,'empleado sin permiso no puede modificar productos');
  await api('/api/restaurant/location',{token:restaurant,method:'PUT',body:{latitude:19.8826,longitude:-103.5998}});
  const product=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Pedido controlado',description:'Prueba',price:100,image:''}});ok(product.status===201,'producto controlado creado');
  const me=await api('/api/restaurant/me',{token:restaurant}),restaurantId=me.data.id;
  const visibility=await api('/api/admin/restaurants/'+restaurantId+'/visibility',{token:admin,method:'PATCH',body:{category:'Comida mexicana',priority:80,featured:true}});ok(visibility.status===200&&visibility.data.featured,'administrador destaca y prioriza restaurante');
  const closed=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'closed',prepMinutes:30,specialHours:'Cierre de prueba'}});ok(closed.status===200,'restaurante puede cerrar pedidos');
  const rejectedClosed=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(rejectedClosed.status===409,'un restaurante cerrado no recibe pedidos');
  const saturated=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'saturated',prepMinutes:30,specialHours:'Alta demanda'}});ok(saturated.status===200&&saturated.data.estimatedPrepMinutes===50,'modo saturado aumenta veinte minutos');
  const publicRestaurants=await api('/api/restaurants');ok(publicRestaurants.data[0]?.id===restaurantId&&publicRestaurants.data[0]?.category==='Comida mexicana'&&publicRestaurants.data[0]?.featured===1&&publicRestaurants.data[0]?.operational_status==='saturated','prioridad, categoría y disponibilidad aparecen en directorio');
  const cancelledOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Pedido que será cancelado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});const cancelled=await api('/api/restaurant/orders/'+cancelledOrder.data.orderId,{token:restaurant,method:'PATCH',body:{status:'cancelled'}});ok(cancelled.status===200,'restaurante cancela un pedido antes de prepararlo');
  const orders=[];
  for(const paymentMethod of ['Efectivo','Transferencia','Tarjeta al recibir']){const created=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod,deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(created.status===201,'pedido creado con '+paymentMethod);ok(created.data.paymentStatus===(paymentMethod==='Transferencia'?'awaiting_confirmation':'pay_on_delivery'),'estado de pago correcto para '+paymentMethod);orders.push({id:created.data.orderId,paymentMethod});if(paymentMethod==='Transferencia'){const paid=await api('/api/restaurant/orders/'+created.data.orderId+'/payment',{token:restaurant,method:'PATCH',body:{}});ok(paid.status===200&&paid.data.paymentStatus==='confirmed','transferencia conciliada manualmente')}for(const status of ['accepted','preparing','ready']){const actor=status==='accepted'&&paymentMethod==='Efectivo'?employee:restaurant;const moved=await api('/api/restaurant/orders/'+created.data.orderId,{token:actor,method:'PATCH',body:{status}});ok(moved.status===200,'pedido '+created.data.orderId+' cambia a '+status)}}
  await Promise.all([api('/api/delivery/location',{token:d1,method:'PUT',body:{latitude:19.88,longitude:-103.60,accuracy:5}}),api('/api/delivery/location',{token:d2,method:'PUT',body:{latitude:19.881,longitude:-103.60,accuracy:5}})]);
  const customerNotices=await api('/api/notifications',{token:customer.data.token});ok(customerNotices.status===200&&customerNotices.data.notifications.some(n=>n.type==='order_ready'),'cliente recibe avisos persistentes del avance');
  const employeeNotices=await api('/api/notifications',{token:employee});ok(employeeNotices.status===200&&employeeNotices.data.notifications.some(n=>n.type==='order_received'),'empleado autorizado recibe aviso de pedido nuevo');
  const readNotices=await api('/api/notifications/read',{token:customer.data.token,method:'PATCH',body:{}});const afterRead=await api('/api/notifications',{token:customer.data.token});ok(readNotices.status===200&&afterRead.data.unread===0,'usuario puede marcar sus avisos como leídos');
  const race=await Promise.all([api('/api/delivery/orders/'+orders[0].id+'/accept',{token:d1,method:'POST'}),api('/api/delivery/orders/'+orders[0].id+'/accept',{token:d2,method:'POST'})]);ok(race.filter(r=>r.status===200).length===1&&race.filter(r=>r.status===409).length===1,'sólo un repartidor gana la aceptación concurrente');
  const winner=race[0].status===200?d1:d2;for(const state of ['delivering','delivered']){const tracking=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token});const moved=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:state,deliveryPin:tracking.data.delivery_pin}});ok(moved.status===200,'entrega avanza a '+state);if(state==='delivering'){const shared=await api('/api/delivery/orders/'+orders[0].id+'/location',{token:winner,method:'PATCH',body:{latitude:19.885,longitude:-103.601,accuracy:5}});ok(shared.status===200,'repartidor comparte ubicación durante entrega')}}
  for(let i=1;i<orders.length;i++){const courier=i%2?d1:d2;const accepted=await api('/api/delivery/orders/'+orders[i].id+'/accept',{token:courier,method:'POST'});ok(accepted.status===200,'repartidor acepta pedido con '+orders[i].paymentMethod);for(const state of ['delivering','delivered']){const tracking=await api('/api/orders/'+orders[i].id+'/tracking',{token:customer.data.token});const moved=await api('/api/delivery/orders/'+orders[i].id,{token:courier,method:'PATCH',body:{status:state,deliveryPin:tracking.data.delivery_pin}});ok(moved.status===200,'flujo '+orders[i].paymentMethod+' termina en '+state)}}
  const closedTracking=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token});ok(closedTracking.status===200&&closedTracking.data.latitude===null&&closedTracking.data.longitude===null&&closedTracking.data.delivery_phone===null,'seguimiento oculta ubicación y teléfono después de entregar');
  const closedRestaurantView=await api('/api/restaurant/me',{token:restaurant});const closedOrder=closedRestaurantView.data.orders.find(item=>item.id===orders[0].id);ok(closedOrder?.customer_phone===null&&closedOrder?.delivery_latitude===null&&closedOrder?.address==='Datos ocultos al cerrar el pedido','restaurante deja de ver datos personales al cerrar el pedido');
  const review=await api('/api/orders/'+orders[0].id+'/review',{token:customer.data.token,method:'POST',body:{restaurantRating:5,deliveryRating:4,tipAmount:20,comment:'Entrega controlada'}});ok(review.status===201&&review.data.tipAmount===20&&review.data.tipMethod==='cash','cliente califica y registra propina en efectivo');
  const duplicateReview=await api('/api/orders/'+orders[0].id+'/review',{token:customer.data.token,method:'POST',body:{restaurantRating:5,tipAmount:0}});ok(duplicateReview.status===409,'un pedido no puede calificarse dos veces');
  const courierHistory=await api('/api/delivery/orders/my',{token:winner});ok(courierHistory.data.find(item=>item.id===orders[0].id)?.tip_amount===20,'repartidor ve la propina registrada');
  const ratedRestaurants=await api('/api/restaurants');ok(ratedRestaurants.data.find(item=>item.id===restaurantId)?.rating===5,'calificación actualiza reputación del restaurante');
  const feedbackBody={category:'error',rating:3,answers:['Sí','Sí','No','Avisos más claros'],comment:'La pantalla del pedido tardó en actualizar',orderId:orders[0].id,anonymous:true,contactAllowed:true};
  const feedback=await api('/api/feedback',{token:customer.data.token,method:'POST',body:feedbackBody});ok(feedback.status===201&&/^[a-f0-9]{24}$/.test(feedback.data.trackingCode),'cliente envía opinión anónima y recibe folio privado');
  const feedbackStatus=await api('/api/feedback/status/'+feedback.data.trackingCode);ok(feedbackStatus.status===200&&feedbackStatus.data.status==='received','folio permite consultar estado de opinión');
  const repeated=await api('/api/feedback',{token:customer.data.token,method:'POST',body:{...feedbackBody,orderId:orders[1].id}});ok(repeated.status===201,'se acepta un segundo reporte del mismo problema');
  const adminFeedback=await api('/api/admin/feedback',{token:admin});const reported=adminFeedback.data.find(item=>item.id===feedback.data.id);ok(adminFeedback.status===200&&reported?.frequency===2&&reported.user_id===null&&reported.contact_email===null,'panel agrupa reportes repetidos y protege el anonimato');
  const feedbackUpdate=await api('/api/admin/feedback/'+feedback.data.id,{token:admin,method:'PATCH',body:{status:'reviewing',severity:'high',adminNotes:'Revisar actualización del seguimiento'}});ok(feedbackUpdate.status===200&&feedbackUpdate.data.severity==='high','administrador clasifica gravedad y avance');
  const updatedFeedbackStatus=await api('/api/feedback/status/'+feedback.data.trackingCode);ok(updatedFeedbackStatus.data.status==='reviewing'&&updatedFeedbackStatus.data.severity==='high','usuario consulta el avance actualizado');
  const issue=await api('/api/order-issues',{token:customer.data.token,method:'POST',body:{orderId:orders[0].id,issueType:'missing_product',description:'Faltó una bebida en la prueba'}});ok(issue.status===201,'cliente reporta problema relacionado con su pedido');
  const issuesAdmin=await api('/api/admin/order-issues',{token:admin});ok(issuesAdmin.data.some(item=>item.id===issue.data.id),'administrador ve el problema reportado');
  const issueUpdated=await api('/api/admin/order-issues/'+issue.data.id,{token:admin,method:'PATCH',body:{status:'resolved',adminNotes:'Resuelto en prueba'}});ok(issueUpdated.status===200,'administrador resuelve el problema');
  const demo=await api('/api/admin/demo/create',{token:admin,method:'POST',body:{}});ok(demo.status===201&&demo.data.status==='received','administrador crea pedido de demostración aislado');
  for(const expected of ['accepted','preparing','ready','assigned','delivering','delivered']){const advanced=await api('/api/admin/demo/'+demo.data.orderId+'/advance',{token:admin,method:'POST',body:{}});ok(advanced.status===200&&advanced.data.status===expected,'demostración avanza a '+expected)}
  const resetDemo=await api('/api/admin/demo',{token:admin,method:'DELETE'});ok(resetDemo.status===200&&resetDemo.data.removed===1,'reinicio elimina únicamente el pedido de demostración');
  const subscriptions=await api('/api/admin/subscriptions',{token:admin});const subscription=subscriptions.data.find(s=>s.restaurant_id===restaurantId);ok(subscription?.registration_fee===50&&subscription?.first_month_fee===100&&subscription?.initial_payment_total===150&&subscription?.promotion_monthly_fee===100&&subscription?.regular_monthly_fee===200,'inscripción y primera mensualidad quedan desglosadas');
  const registration=await api('/api/admin/subscriptions/'+restaurantId+'/payment',{token:admin,method:'PATCH',body:{acceptedTerms:true}});ok(registration.status===200&&registration.data.firstMonthIncluded,'inscripción confirmada incluye primera mensualidad');
  let settlement=await api('/api/restaurant/settlement',{token:restaurant});ok(settlement.status===200&&settlement.data.days[0]?.orders_count===3&&settlement.data.days[0]?.sales===300&&settlement.data.days[0]?.cancellations===1&&settlement.data.days[0]?.reversed_amount===135,'corte excluye ventas canceladas y conserva su reversión');
  const pendingSettlements=await api('/api/admin/settlements',{token:admin});const pendingCut=pendingSettlements.data.pending.find(c=>c.restaurant_id===restaurantId);ok(pendingCut?.amount===300,'administrador ve únicamente el saldo válido pendiente');
  const proof='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
  const paidCut=await api('/api/admin/settlements',{token:admin,method:'POST',body:{restaurantId,periodDate:pendingCut.period_date,reference:'TRX-PRUEBA-001',proofDataUrl:proof}});ok(paidCut.status===201&&paidCut.data.amount===300,'administrador registra fecha, referencia y comprobante del corte');
  settlement=await api('/api/restaurant/settlement',{token:restaurant});ok(settlement.data.days[0]?.pending_due===0&&settlement.data.days[0]?.paid_due===300&&settlement.data.batches[0]?.reference==='TRX-PRUEBA-001','restaurante consulta corte pagado e historial');
  const proofResponse=await fetch(base+'/api/settlements/'+paidCut.data.batchId+'/proof',{headers:{Authorization:'Bearer '+restaurant}});ok(proofResponse.status===200&&String(proofResponse.headers.get('content-type')).startsWith('image/'),'comprobante privado sólo se obtiene con sesión autorizada');
  const duplicateCut=await api('/api/admin/settlements',{token:admin,method:'POST',body:{restaurantId,periodDate:pendingCut.period_date,reference:'DUPLICADO'}});ok(duplicateCut.status===409,'un corte pagado no puede conciliarse dos veces');
  const history=await api('/api/orders/my',{token:customer.data.token});for(const order of orders){const saved=history.data.find(item=>item.id===order.id);ok(saved?.status==='delivered','pedido '+order.paymentMethod+' quedó entregado');ok(saved?.payment_status===(order.paymentMethod==='Transferencia'?'confirmed':'paid'),'pago final correcto para '+order.paymentMethod)}
  console.log('\nTodas las pruebas controladas terminaron correctamente.');
}
run().catch(error=>{console.error('PRUEBA FALLIDA:',error.message);process.exitCode=1}).finally(()=>{child.kill();setTimeout(()=>{for(const suffix of ['', '-wal','-shm'])try{fs.unlinkSync(dbFile+suffix)}catch(e){}},300)});

