const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),{spawn}=require('child_process'),crypto=require('crypto'),Database=require('better-sqlite3'),sharp=require('sharp');
const root=__dirname,dbFile=path.join(os.tmpdir(),'test-come-sayula.db'),port=3199,mailPort=3200,paymentPort=3201,base=`http://127.0.0.1:${port}`,mailRequests=[],paymentRequests=[];let paymentReference='',paymentAmount=0;
const mailServer=http.createServer((req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{mailRequests.push({url:req.url,authorization:req.headers.authorization,body:JSON.parse(body)});res.writeHead(202);res.end();});});
const makePdfDataUrl=text=>{const safe=String(text).replace(/([\\()])/g,'\\$1'),stream=`BT\n/F1 12 Tf\n72 720 Td\n(${safe}) Tj\nET`,objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((object,index)=>{offsets[index+1]=Buffer.byteLength(pdf);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=Buffer.byteLength(pdf);pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(offset=>String(offset).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return 'data:application/pdf;base64,'+Buffer.from(pdf).toString('base64')};
mailServer.listen(mailPort,'127.0.0.1');
const paymentServer=http.createServer((req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{if(req.method==='POST'&&req.url==='/checkout/preferences'){const data=JSON.parse(body);paymentReference=data.external_reference;paymentAmount=data.items[0].unit_price;paymentRequests.push({method:req.method,url:req.url,authorization:req.headers.authorization,idempotency:req.headers['x-idempotency-key'],body:data});res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({id:'pref-test-1',sandbox_init_point:'https://sandbox.mercadopago.test/checkout'}))}if(req.method==='GET'&&req.url==='/v1/payments/pay-test-1'){paymentRequests.push({method:req.method,url:req.url,authorization:req.headers.authorization});res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({id:'pay-test-1',status:'approved',external_reference:paymentReference,transaction_amount:paymentAmount,currency_id:'MXN'}))}res.writeHead(404);res.end()})});
paymentServer.listen(paymentPort,'127.0.0.1');
for(const suffix of ['', '-wal','-shm'])try{fs.unlinkSync(dbFile+suffix)}catch(e){}
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,OPENAI_API_KEY:'',DATA_DIR:os.tmpdir(),DB_FILE:dbFile,PORT:String(port),ADMIN_EMAIL:'admin@test.local',ADMIN_PASSWORD:'Admin-Pruebas-2026',DISABLE_AUTOMATIC_BACKUP:'1',DEV_SHOW_RESET_TOKEN:'1',SENDGRID_API_KEY:'SG.test-only-not-a-secret',SENDGRID_FROM_EMAIL:'correo@test.local',SENDGRID_FROM_NAME:'COME SAYULA pruebas',SENDGRID_API_URL:`http://127.0.0.1:${mailPort}/v3/mail/send`,MERCADOPAGO_MODE:'test',MERCADOPAGO_TEST_ACCESS_TOKEN:'TEST-token-falso',MERCADOPAGO_API_BASE:`http://127.0.0.1:${paymentPort}`,MERCADOPAGO_WEBHOOK_SECRET:'webhook-secret-for-tests',PAYMENT_PROVIDER_ENABLED:'1',NOTIFICATION_WORKER_INTERVAL_MS:'100',ORDER_RATE_LIMIT_MAX:'100'},stdio:['ignore','pipe','pipe']});
let serverError='';child.stderr.on('data',chunk=>serverError+=chunk.toString());
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function api(url,{token,method='GET',body}={}){const response=await fetch(base+url,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});let data={};try{data=await response.json()}catch(e){}return {status:response.status,data,headers:response.headers};}
function ok(condition,message){if(!condition)throw new Error(message);console.log('✓ '+message)}
async function login(email,password,role){const r=await api('/api/auth/login',{method:'POST',body:{email,password,role}});ok(r.status===200,'inicio de sesión '+role);return r.data.token}
async function run(){
  for(let i=0;i<100;i++){await wait(150);try{if((await api('/api/health')).status===200)break}catch(e){}if(i===99)throw new Error('El servidor de prueba no inició: '+serverError.trim())}
  const healthHeaders=await api('/api/health');ok(healthHeaders.headers.get('cache-control')?.includes('no-store')&&healthHeaders.headers.get('x-content-type-options')==='nosniff'&&healthHeaders.headers.get('content-security-policy'),'API aplica encabezados de seguridad y evita caché sensible');
  const publicConfig=await api('/api/public-config');ok(publicConfig.status===200&&publicConfig.data.onlinePaymentEnabled===true&&publicConfig.data.onlinePaymentMode==='test','carrito recibe el estado real del proveedor de pagos sin exponer secretos');
  const legalResponse=await fetch(base+'/legal.html'),legalText=await legalResponse.text();ok(legalResponse.status===200&&legalText.includes('Versión vigente: 8 de septiembre de 2026')&&legalText.includes('Solicitud ARCO')&&!legalText.includes('Documento previo a producción'),'aviso integral publica responsable, derechos y versión vigente sin texto pendiente');
  const weakPassword=await api('/api/auth/register',{method:'POST',body:{name:'Clave débil',email:'debil@test.local',password:'Corta-123',role:'customer',termsAccepted:true}});ok(weakPassword.status===400,'registro exige contraseña de al menos diez caracteres');
  const denied=await api('/api/auth/register',{method:'POST',body:{name:'Intruso',email:'staff-public@test.local',password:'Contrasena12',role:'delivery',termsAccepted:true}});ok(denied.status===403,'registro público bloquea roles operativos');
  const customer=await api('/api/auth/register',{method:'POST',body:{name:'Cliente Prueba',email:'cliente@test.local',phone:'3410000000',password:'Cliente-Prueba-12',role:'customer',termsAccepted:true}});ok(customer.status===201,'registro público permite clientes con consentimiento');
  const consentDb=new Database(dbFile,{readonly:true}),consent=consentDb.prepare("SELECT terms_version FROM users WHERE email='cliente@test.local'").get();consentDb.close();ok(consent?.terms_version==='2026-09-08','registro conserva la versión exacta de términos aceptada');
  const admin=await login('admin@test.local','Admin-Pruebas-2026','admin'),adminClaims=JSON.parse(Buffer.from(admin.split('.')[1],'base64url').toString());ok(adminClaims.exp-adminClaims.iat===30*24*60*60,'sesión recordada permanece válida durante 30 días');const sessionScript=await fetch(base+'/session.js').then(r=>r.text());ok(sessionScript.includes('localStorage')&&sessionScript.includes('CS_SESSION'),'PWA conserva la cuenta y sincroniza el cierre de sesión');
  const previousCustomerToken=customer.data.token,forgotten=await api('/api/auth/forgot-password',{method:'POST',body:{email:'cliente@test.local'}});ok(forgotten.status===200&&!forgotten.data.developmentToken,'recuperación con proveedor no expone el token en la respuesta');
  const sentMail=mailRequests[0],resetUrl=sentMail?.body?.content?.find(item=>item.type==='text/plain')?.value?.match(/https?:\/\/[^\s]+/)?.[0],resetToken=new URL(resetUrl).searchParams.get('token');ok(sentMail?.url==='/v3/mail/send'&&sentMail.authorization==='Bearer SG.test-only-not-a-secret'&&sentMail.body.personalizations[0].to[0].email==='cliente@test.local'&&resetToken,'recuperación entrega por SendGrid un enlace temporal al correo correcto');
  const unknownForgotten=await api('/api/auth/forgot-password',{method:'POST',body:{email:'no-existe@test.local'}});ok(unknownForgotten.status===200&&mailRequests.length===1,'recuperación no revela cuentas inexistentes ni intenta enviarles correo');
  const reset=await api('/api/auth/reset-password',{method:'POST',body:{token:resetToken,password:'Cliente-Nueva-2026'}});ok(reset.status===200,'enlace válido cambia la contraseña');
  const oldSession=await api('/api/orders/my',{token:previousCustomerToken}),reusedReset=await api('/api/auth/reset-password',{method:'POST',body:{token:resetToken,password:'Otra-Clave-2026'}});ok(oldSession.status===401&&reusedReset.status===400,'cambio invalida sesiones anteriores y el enlace sólo se usa una vez');
  customer.data.token=await login('cliente@test.local','Cliente-Nueva-2026','customer');
  const customerTokenBeforeChange=customer.data.token,ownPassword=await api('/api/auth/password',{token:customer.data.token,method:'PATCH',body:{currentPassword:'Cliente-Nueva-2026',newPassword:'Cliente-Final-2026'}});ok(ownPassword.status===200&&ownPassword.data.token,'cliente cambia su propia contraseña y recibe una sesión nueva');
  const previousOwnSession=await api('/api/orders/my',{token:customerTokenBeforeChange});ok(previousOwnSession.status===401,'cambio propio cierra las demás sesiones');customer.data.token=ownPassword.data.token;
  const aiStatus=await api('/api/ai/status',{token:admin});ok(aiStatus.status===200&&aiStatus.data.enabled===false,'asistente informa cuando falta configuración');
  const aiUnavailable=await api('/api/ai/chat',{token:admin,method:'POST',body:{message:'Resume la operación'}});ok(aiUnavailable.status===503,'asistente falla de forma segura sin clave');
  const pushKey=await api('/api/push/public-key',{token:admin});ok(pushKey.status===200&&typeof pushKey.data.publicKey==='string'&&pushKey.data.publicKey.length>40,'servidor prepara notificaciones móviles cifradas');
  const invalidPush=await api('/api/push/subscribe',{token:admin,method:'POST',body:{subscription:{endpoint:'http://inseguro.local',keys:{p256dh:'corta',auth:'corta'}}}});ok(invalidPush.status===400,'servidor rechaza suscripciones push inseguras o incompletas');
  for(const user of [{name:'Restaurante Prueba',email:'rest@test.local',phone:'3411',password:'Restaurante-12',role:'restaurant'},{name:'Repartidor Uno',email:'rep1@test.local',password:'Repartidor-uno-12',role:'delivery'},{name:'Repartidor Dos',email:'rep2@test.local',password:'Repartidor-dos-12',role:'delivery'}]){const c=await api('/api/admin/users',{token:admin,method:'POST',body:user});ok(c.status===201,'administrador crea '+user.role);const a=await api('/api/admin/users/'+c.data.id+'/status',{token:admin,method:'PATCH',body:{status:'approved'}});ok(a.status===200,'administrador aprueba '+user.email)}
  const restaurant=await login('rest@test.local','Restaurante-12','restaurant'),d1=await login('rep1@test.local','Repartidor-uno-12','delivery'),d2=await login('rep2@test.local','Repartidor-dos-12','delivery');
  const initialTrust=await api('/api/trust/me',{token:customer.data.token});ok(initialTrust.status===200&&initialTrust.data.score===50&&initialTrust.data.cashLimit===500&&initialTrust.data.level==='new','cliente nuevo ve nivel de confianza y límite inicial de efectivo');
  const profileSaved=await api('/api/delivery/profile',{token:d1,method:'PUT',body:{vehicleType:'motorcycle',vehicleDescription:'Motocicleta roja con caja COME SAYULA'}}),profileRead=await api('/api/delivery/profile',{token:d1});ok(profileSaved.status===200&&profileRead.status===200&&profileRead.data.verification_status==='verified'&&profileRead.data.internal_number.startsWith('CS-')&&profileRead.data.vehicle_type==='motorcycle','repartidor configura vehículo y conserva identidad interna verificada');
  const invalidCourierLimit=await api('/api/admin/delivery-couriers/999999/profile',{token:admin,method:'PATCH',body:{verificationStatus:'verified',maxActiveOrders:4}});ok(invalidCourierLimit.status===400,'administración no puede fijar un límite inseguro de entregas simultáneas');
  const customerAdminDenied=await api('/api/admin/scheduled-orders',{token:customer.data.token}),deliveryRestaurantDenied=await api('/api/restaurant/me',{token:d1});ok(customerAdminDenied.status===403&&deliveryRestaurantDenied.status===403,'roles no pueden consultar paneles ajenos');
  const savedAddress=await api('/api/customer/addresses',{token:customer.data.token,method:'POST',body:{label:'Casa',address:'Calle de prueba 123',reference:'Portón naranja',latitude:19.89,longitude:-103.60,isDefault:true}});ok(savedAddress.status===201&&savedAddress.data.is_default===1,'cliente guarda domicilio con ubicación exacta');
  const customerAddresses=await api('/api/customer/addresses',{token:customer.data.token});ok(customerAddresses.status===200&&customerAddresses.data.length===1&&customerAddresses.data[0].reference==='Portón naranja','cliente consulta únicamente sus direcciones');
  const courierAddresses=await api('/api/customer/addresses',{token:d1});ok(courierAddresses.status===403,'repartidor no puede consultar direcciones guardadas');
  const employeeCreated=await api('/api/restaurant/employees',{token:restaurant,method:'POST',body:{name:'Empleado Pedidos',email:'empleado@test.local',phone:'3412',password:'Empleado-Seguro-12',positionRole:'kitchen',canViewFinance:true}});ok(employeeCreated.status===201&&employeeCreated.data.positionRole==='kitchen','dueño crea acceso individual con perfil de Cocina');
  const employee=await login('empleado@test.local','Empleado-Seguro-12','restaurant');
  const employeePanel=await api('/api/restaurant/me',{token:employee});ok(employeePanel.status===200&&employeePanel.data.access?.isOwner===false&&employeePanel.data.access?.canManageOrders===true,'empleado entra al negocio con permisos propios');
  const employeeFinance=await api('/api/restaurant/settlement',{token:employee});ok(employeeFinance.status===403,'empleado sin permiso no puede ver cortes');
  const employeeProduct=await api('/api/restaurant/products',{token:employee,method:'POST',body:{name:'No autorizado',price:20}});ok(employeeProduct.status===403,'empleado sin permiso no puede modificar productos');
  const employeePos=await api('/api/restaurant/pos',{token:employee});ok(employeePos.status===403,'empleado sin permiso no puede usar el punto de venta');
  const invalidEmployeeRole=await api('/api/restaurant/employees/'+employeeCreated.data.id,{token:restaurant,method:'PATCH',body:{positionRole:'owner',active:true}});ok(invalidEmployeeRole.status===400,'servidor impide asignar el perfil reservado de Dueño');const cashierUpdate=await api('/api/restaurant/employees/'+employeeCreated.data.id,{token:restaurant,method:'PATCH',body:{positionRole:'cashier',canViewFinance:true,active:true}}),cashierPanel=await api('/api/restaurant/me',{token:employee}),cashierPos=await api('/api/restaurant/pos',{token:employee}),cashierFinance=await api('/api/restaurant/settlement',{token:employee});ok(cashierUpdate.status===200&&cashierPanel.data.access.canUsePos===true&&cashierPanel.data.access.canViewFinance===false&&cashierPos.status===200&&cashierFinance.status===403,'perfil de Caja permite pedidos y punto de venta sin exponer finanzas');await api('/api/restaurant/employees/'+employeeCreated.data.id,{token:restaurant,method:'PATCH',body:{positionRole:'custom',canManageOrders:true,canManageProducts:false,canViewFinance:false,canUsePos:false,active:true}});
  await api('/api/restaurant/location',{token:restaurant,method:'PUT',body:{latitude:19.8826,longitude:-103.5998}});
  const sampleImage='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
  const optimizedImage=await api('/api/restaurant/uploads',{token:restaurant,method:'POST',body:{dataUrl:sampleImage}});ok(optimizedImage.status===201&&optimizedImage.data.url.endsWith('.webp')&&optimizedImage.data.storedBytes>0,'fotografía se valida y optimiza automáticamente');
  const storedImage=await fetch(base+optimizedImage.data.url);ok(storedImage.status===200&&storedImage.headers.get('content-type')==='image/webp','servidor entrega la fotografía optimizada');
  const storage=await api('/api/admin/storage',{token:admin});ok(storage.status===200&&storage.data.capacityBytes===1073741824&&storage.data.uploadsBytes>0,'administrador consulta capacidad y uso del disco');
  const product=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Pedido controlado',description:'Prueba',price:100,image:''}});ok(product.status===201,'producto controlado creado');
  const drink=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Agua fresca',description:'Bebida de prueba',price:25,image:'',category:'Bebidas'}});ok(drink.status===201&&drink.data.category==='Bebidas','restaurante clasifica bebidas en su menú');
  const alcohol=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Bebida para adultos',description:'Prueba protegida',price:45,image:'',category:'Bebidas alcohólicas'}});ok(alcohol.status===201&&alcohol.data.category==='Bebidas alcohólicas','restaurante clasifica bebidas alcohólicas');
  const cashOpened=await api('/api/restaurant/cash/open',{token:restaurant,method:'POST',body:{openingAmount:500,note:'Inicio de turno'}});ok(cashOpened.status===201&&cashOpened.data.currentExpected===500,'restaurante abre caja con fondo inicial');
  const cashMovement=await api('/api/restaurant/cash/movements',{token:restaurant,method:'POST',body:{type:'withdrawal',amount:50,reason:'Compra de insumos'}});ok(cashMovement.status===201&&cashMovement.data.currentExpected===450,'caja registra retiros con motivo');
  const posRequest=crypto.randomUUID(),posDenied=await api('/api/restaurant/pos/sales',{token:restaurant,method:'POST',body:{items:[{productId:alcohol.data.id,quantity:2}],paymentMethod:'Efectivo',clientRequestId:posRequest,ageConfirmed:false}});ok(posDenied.status===403,'punto de venta exige verificación de mayoría de edad');
  const posCardRejected=await api('/api/restaurant/pos/sales',{token:restaurant,method:'POST',body:{items:[{productId:alcohol.data.id,quantity:1}],paymentMethod:'Tarjeta',clientRequestId:crypto.randomUUID(),ageConfirmed:true,cardNumber:'NO-GUARDAR',cvv:'XXX'}});ok(posCardRejected.status===400,'punto de venta rechaza datos sensibles de tarjeta');
  const posSale=await api('/api/restaurant/pos/sales',{token:restaurant,method:'POST',body:{items:[{productId:alcohol.data.id,quantity:2}],paymentMethod:'Efectivo',clientRequestId:posRequest,ageConfirmed:true}});ok(posSale.status===201&&posSale.data.total===90&&posSale.data.receiptNumber.startsWith('POS-'),'punto de venta registra venta local con folio independiente');
  const posRepeated=await api('/api/restaurant/pos/sales',{token:restaurant,method:'POST',body:{items:[{productId:alcohol.data.id,quantity:2}],paymentMethod:'Efectivo',clientRequestId:posRequest,ageConfirmed:true}});ok(posRepeated.status===200&&posRepeated.data.repeated,'punto de venta evita cobro duplicado');
  let posPanel=await api('/api/restaurant/pos',{token:restaurant});ok(posPanel.data.today.total===90&&posPanel.data.sales[0].items[0].category==='Bebidas alcohólicas','venta local aparece en resumen sin pedido de reparto');
  const cashStatus=await api('/api/restaurant/cash',{token:restaurant});ok(cashStatus.status===200&&cashStatus.data.open.currentExpected===540,'caja suma automáticamente ventas en efectivo');
  const cashClosed=await api('/api/restaurant/cash/close',{token:restaurant,method:'POST',body:{countedAmount:535,note:'Cierre controlado'}});ok(cashClosed.status===200&&cashClosed.data.difference_amount===-5&&cashClosed.data.status==='closed','cierre compara efectivo contado contra esperado');
  const analytics=await api('/api/restaurant/analytics?days=7',{token:restaurant});ok(analytics.status===200&&analytics.data.pos.total===90&&analytics.data.cash.net_difference===-5&&analytics.data.topProducts.some(item=>item.product_name==='Bebida para adultos'),'estadísticas integran mostrador, productos y diferencias de caja');
  const employeeAnalytics=await api('/api/restaurant/analytics?days=7',{token:employee});ok(employeeAnalytics.status===403,'estadísticas respetan permisos financieros');
  const optimization=await api('/api/restaurant/optimization?days=30',{token:restaurant}),employeeOptimization=await api('/api/restaurant/optimization?days=30',{token:employee});ok(optimization.status===200&&optimization.data.confidence==='insufficient'&&optimization.data.minimumSample===10&&optimization.data.automaticChanges===false&&optimization.data.recommendations[0].type==='data','optimización no recomienda cambios con una muestra insuficiente');ok(employeeOptimization.status===403,'recomendaciones operativas respetan permisos financieros');
  const posVoid=await api('/api/restaurant/pos/sales/'+posSale.data.id+'/void',{token:restaurant,method:'POST',body:{reason:'Cancelación de prueba'}});posPanel=await api('/api/restaurant/pos',{token:restaurant});ok(posVoid.status===200&&posPanel.data.today.total===0&&posPanel.data.today.voided===1,'venta local puede anularse con motivo y auditoría');
  const me=await api('/api/restaurant/me',{token:restaurant}),restaurantId=me.data.id,publicInfoDefault=await api('/api/restaurants/'+me.data.id+'/menu');ok(publicInfoDefault.data.restaurant.phone===me.data.phone&&Number(publicInfoDefault.data.restaurant.latitude)===Number(me.data.latitude),'restaurante existente conserva teléfono y ubicación públicos por compatibilidad');const invalidPublicInfo=await api('/api/restaurant/public-settings',{token:restaurant,method:'PUT',body:{publicAddress:'no',publicPhone:false,publicLocation:false}});ok(invalidPublicInfo.status===400,'servidor exige opciones de privacidad booleanas');const hiddenPublicInfo=await api('/api/restaurant/public-settings',{token:restaurant,method:'PUT',body:{publicAddress:false,publicPhone:false,publicLocation:false}}),hiddenPublicMenu=await api('/api/restaurants/'+me.data.id+'/menu'),privateOwnerView=await api('/api/restaurant/me',{token:restaurant});ok(hiddenPublicInfo.status===200&&hiddenPublicMenu.data.restaurant.phone===null&&hiddenPublicMenu.data.restaurant.latitude===null&&privateOwnerView.data.phone===me.data.phone,'privacidad oculta datos al cliente sin quitarlos del panel del dueño');const restoredPublicInfo=await api('/api/restaurant/public-settings',{token:restaurant,method:'PUT',body:{publicAddress:true,publicPhone:true,publicLocation:true}}),restoredPublicMenu=await api('/api/restaurants/'+me.data.id+'/menu');ok(restoredPublicInfo.status===200&&restoredPublicMenu.data.restaurant.phone===me.data.phone&&Number(restoredPublicMenu.data.restaurant.latitude)===Number(me.data.latitude),'dueño puede restaurar información pública');const customerHome=await fetch(base+'/home3.html').then(response=>response.text());ok(customerHome.includes('Ver ubicación')&&customerHome.includes('Contactar restaurante')&&customerHome.includes('perfilPublico.address'),'menú y confirmación muestran acciones e información pública');
  const deniedHours=await api('/api/restaurant/business-hours',{token:employee}),invalidHours=await api('/api/restaurant/business-hours',{token:restaurant,method:'PUT',body:{hours:Array.from({length:7},(_,weekday)=>({weekday,closed:false,opensAt:'20:00',closesAt:'09:00'}))}});ok(deniedHours.status===403&&invalidHours.status===400,'horarios semanales protegen al dueño y validan apertura antes del cierre');
  const closedHours=await api('/api/restaurant/business-hours',{token:restaurant,method:'PUT',body:{hours:Array.from({length:7},(_,weekday)=>({weekday,closed:true,opensAt:'09:00',closesAt:'20:00'}))}}),closedImmediate=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Fuera de horario',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}}),closedScheduled=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Programado fuera de horario',paymentMethod:'Efectivo',orderTiming:'scheduled',scheduledFor:new Date(Date.now()+2*60*60*1000).toISOString(),deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(closedHours.status===200&&closedImmediate.status===409&&closedScheduled.status===409,'servidor bloquea pedidos inmediatos y programados en días cerrados');const resetHoursDb=new Database(dbFile);resetHoursDb.prepare('DELETE FROM restaurant_business_hours WHERE restaurant_id=?').run(restaurantId);resetHoursDb.close();
  const legacyPublicHours=await api('/api/restaurants/'+restaurantId+'/business-hours');ok(legacyPublicHours.status===200&&legacyPublicHours.data.configured===false&&legacyPublicHours.data.openNow===true,'restaurante sin horario conserva disponibilidad compatible');
  await api('/api/restaurant/business-hours',{token:restaurant,method:'PUT',body:{hours:Array.from({length:7},(_,weekday)=>({weekday,closed:true,opensAt:'09:00',closesAt:'20:00'}))}});const publicClosedHours=await api('/api/restaurants/'+restaurantId+'/business-hours');ok(publicClosedHours.status===200&&publicClosedHours.data.configured===true&&publicClosedHours.data.openNow===false&&publicClosedHours.data.timeZone==='America/Mexico_City','cliente consulta horario semanal y estado cerrado en Sayula');const clearPublicHoursDb=new Database(dbFile);clearPublicHoursDb.prepare('DELETE FROM restaurant_business_hours WHERE restaurant_id=?').run(restaurantId);clearPublicHoursDb.close();
  const specialInstant=new Date(Date.now()+2*60*60*1000),specialParts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(specialInstant),specialDate=['year','month','day'].map(type=>specialParts.find(part=>part.type===type).value).join('-'),specialClosed=await api('/api/restaurant/special-hours',{token:restaurant,method:'POST',body:{date:specialDate,closed:true,note:'Festivo de prueba'}}),specialOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Fecha especial',paymentMethod:'Efectivo',orderTiming:'scheduled',scheduledFor:specialInstant.toISOString(),deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}}),publicSpecial=await api('/api/restaurants/'+restaurantId+'/business-hours');ok(specialClosed.status===201&&specialOrder.status===409&&publicSpecial.data.specialHours.some(row=>row.service_date===specialDate),'fecha especial cerrada bloquea pedidos programados y se muestra al cliente');const specialList=await api('/api/restaurant/special-hours',{token:restaurant}),removedSpecial=await api('/api/restaurant/special-hours/'+specialList.data[0].id,{token:restaurant,method:'DELETE'});ok(removedSpecial.status===200,'restaurante puede eliminar una excepción futura');
  const deniedDraft=await api('/api/restaurant/menu-drafts',{token:employee,method:'POST',body:{sourceType:'text',content:'Sin permiso | 20'}});ok(deniedDraft.status===403,'empleado sin permiso no puede importar menús');
  const beforeDraftMenu=await api('/api/restaurants/'+restaurantId+'/menu'),draft=await api('/api/restaurant/menu-drafts',{token:restaurant,method:'POST',body:{sourceType:'text',sourceName:'Menú controlado',content:'Torta ahogada | 75 | Comida | Receta local\nProducto incompleto'}});ok(draft.status===201&&draft.data.itemCount===2&&draft.data.errorCount===1,'importación crea borrador y detecta renglones inválidos');
  const afterDraftMenu=await api('/api/restaurants/'+restaurantId+'/menu');ok(afterDraftMenu.data.products.length===beforeDraftMenu.data.products.length,'borrador nunca publica productos automáticamente');
  let draftDetail=await api('/api/restaurant/menu-drafts/'+draft.data.id,{token:restaurant}),blockedPublish=await api('/api/restaurant/menu-drafts/'+draft.data.id+'/publish',{token:restaurant,method:'POST'});ok(blockedPublish.status===409,'servidor impide publicar un borrador con errores seleccionados');
  const invalidDraftItem=draftDetail.data.items.find(item=>item.validation_error),fixedDraftItem=await api('/api/restaurant/menu-drafts/'+draft.data.id+'/items/'+invalidDraftItem.id,{token:restaurant,method:'PATCH',body:{name:'Agua de jamaica',price:22,category:'Bebidas',description:'Vaso grande',selected:true}});ok(fixedDraftItem.status===200&&!fixedDraftItem.data.validation_error,'restaurante corrige el borrador antes de publicarlo');
  const publishedDraft=await api('/api/restaurant/menu-drafts/'+draft.data.id+'/publish',{token:restaurant,method:'POST'}),publishedMenu=await api('/api/restaurants/'+restaurantId+'/menu'),duplicatePublish=await api('/api/restaurant/menu-drafts/'+draft.data.id+'/publish',{token:restaurant,method:'POST'});ok(publishedDraft.status===200&&publishedDraft.data.publishedCount===2&&publishedMenu.data.products.some(item=>item.name==='Torta ahogada'),'confirmación manual publica los productos validados');ok(duplicatePublish.status===409,'un borrador no puede publicarse dos veces');
  const tsvDraft=await api('/api/restaurant/menu-drafts',{token:restaurant,method:'POST',body:{sourceType:'tsv',sourceName:'menu-exportado.tsv',content:'Nombre\tPrecio\tCategoría\tDescripción\nPozole\t95\tComida\tReceta del día\nFlan\t40\tPostres\tPorción individual'}});ok(tsvDraft.status===201,'servidor acepta archivos TSV compatibles');ok(tsvDraft.data.itemCount===2&&tsvDraft.data.errorCount===0,'TSV detecta dos productos válidos');const tsvDetail=await api('/api/restaurant/menu-drafts/'+tsvDraft.data.id,{token:restaurant});ok(tsvDetail.data.items?.[1]?.category==='Postres','TSV conserva categorías y crea sólo un borrador');const unsupportedDraft=await api('/api/restaurant/menu-drafts',{token:restaurant,method:'POST',body:{sourceType:'xlsx',content:'archivo no compatible'}});ok(unsupportedDraft.status===400,'servidor rechaza tipos de archivo no compatibles');const pdfBefore=await api('/api/restaurants/'+restaurantId+'/menu'),pdfDraft=await api('/api/restaurant/menu-drafts/pdf',{token:restaurant,method:'POST',body:{sourceName:'menu-prueba.pdf',dataUrl:makePdfDataUrl('Enchiladas | 85 | Comida | Orden de prueba')}}),pdfAfter=await api('/api/restaurants/'+restaurantId+'/menu');ok(pdfDraft.status===201&&pdfDraft.data.pageCount===1&&pdfDraft.data.itemCount>=1,'PDF con texto crea un borrador local');ok(pdfAfter.data.products.length===pdfBefore.data.products.length,'importar PDF nunca publica productos automáticamente');const fakePdf=await api('/api/restaurant/menu-drafts/pdf',{token:restaurant,method:'POST',body:{sourceName:'falso.pdf',dataUrl:'data:application/pdf;base64,'+Buffer.from('no es pdf').toString('base64')}});ok(fakePdf.status===400,'servidor rechaza archivos falsos aunque declaren tipo PDF');const ocrPng=await sharp(Buffer.from('<svg width="1400" height="300" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" fill="white"/><text x="45" y="180" font-family="Arial" font-size="82" fill="black">TACOS | 25 | COMIDA</text></svg>')).png().toBuffer(),ocrBefore=await api('/api/restaurants/'+restaurantId+'/menu'),ocrDraft=await api('/api/restaurant/menu-drafts/ocr',{token:restaurant,method:'POST',body:{sourceName:'foto-menu.png',dataUrl:'data:image/png;base64,'+ocrPng.toString('base64')}}),ocrAfter=await api('/api/restaurants/'+restaurantId+'/menu');ok(ocrDraft.status===201&&ocrDraft.data.itemCount>=1&&Number.isFinite(ocrDraft.data.confidence),'OCR local en español crea un borrador desde una imagen');ok(ocrAfter.data.products.length===ocrBefore.data.products.length,'OCR nunca publica productos automáticamente');const fakeImage=await api('/api/restaurant/menu-drafts/ocr',{token:restaurant,method:'POST',body:{sourceName:'falsa.png',dataUrl:'data:image/png;base64,'+Buffer.from('no es imagen').toString('base64')}});ok(fakeImage.status===400,'OCR rechaza archivos falsos aunque declaren tipo imagen');
  const largeProduct=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Pedido grande controlado',description:'Prueba de riesgo',price:1300,image:''}}),largeCash=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:largeProduct.data.id,quantity:1}],address:'Pedido grande de prueba',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}}),largeTransfer=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:largeProduct.data.id,quantity:1}],address:'Pedido grande de prueba',paymentMethod:'Transferencia',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(largeCash.status===409&&largeCash.data.cashLimit===500&&largeTransfer.status===201,'pedido grande bloquea efectivo sobre el límite pero permite un método trazable');const largeRisk=await api('/api/admin/trust',{token:admin});ok(largeRisk.data.risks.some(r=>r.order_id===largeTransfer.data.orderId&&r.signals.some(s=>s.includes('monto alto'))),'administración ve señales explicables sin suspensión automática');const riskIsolation=new Database(dbFile);riskIsolation.prepare('UPDATE orders SET is_demo=1 WHERE id=?').run(largeTransfer.data.orderId);riskIsolation.close();
  const visibility=await api('/api/admin/restaurants/'+restaurantId+'/visibility',{token:admin,method:'PATCH',body:{category:'Comida mexicana',priority:80,featured:true}});ok(visibility.status===200&&visibility.data.featured,'administrador destaca y prioriza restaurante');
  const closed=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'closed',prepMinutes:30,specialHours:'Cierre de prueba'}});ok(closed.status===200,'restaurante puede cerrar pedidos');
  const rejectedClosed=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(rejectedClosed.status===409,'un restaurante cerrado no recibe pedidos');
  const saturated=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'saturated',prepMinutes:30,specialHours:'Alta demanda'}});ok(saturated.status===200&&saturated.data.estimatedPrepMinutes===50,'modo saturado aumenta veinte minutos');
  const publicRestaurants=await api('/api/restaurants');ok(publicRestaurants.data[0]?.id===restaurantId&&publicRestaurants.data[0]?.category==='Comida mexicana'&&publicRestaurants.data[0]?.featured===1&&publicRestaurants.data[0]?.operational_status==='saturated','prioridad, categoría y disponibilidad aparecen en directorio');
  const publicMenu=await api('/api/restaurants/'+restaurantId+'/menu');ok(publicMenu.data.products.some(p=>p.category==='Bebidas')&&publicMenu.data.products.some(p=>p.category==='Bebidas alcohólicas'),'clientes reciben las nuevas categorías del menú');
  const invalidAutoLimit=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'open',prepMinutes:30,autoSaturationEnabled:true,autoSaturationLimit:0}});ok(invalidAutoLimit.status===400,'servidor rechaza un límite de saturación inseguro');const autoConfig=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'open',prepMinutes:30,specialHours:'',autoSaturationEnabled:true,autoSaturationLimit:1}}),loadOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Prueba de carga automática',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}}),autoDirectory=await api('/api/restaurants'),autoMenu=await api('/api/restaurants/'+restaurantId+'/menu'),autoPanel=await api('/api/restaurant/me',{token:restaurant});ok(autoConfig.status===200&&loadOrder.status===201&&autoDirectory.data.find(r=>r.id===restaurantId)?.auto_saturated===true&&autoMenu.data.restaurant.estimatedPrepMinutes===50&&autoPanel.data.active_order_count===1,'un pedido activo alcanza el límite y activa saturación con veinte minutos adicionales');await api('/api/orders/'+loadOrder.data.orderId+'/cancel',{token:customer.data.token,method:'POST',body:{reason:'Fin de prueba de carga'}});const recoveredLoad=await api('/api/restaurants/'+restaurantId+'/menu');ok(recoveredLoad.data.restaurant.auto_saturated===false&&recoveredLoad.data.restaurant.operational_status==='open','la saturación automática se retira al bajar la carga');await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'saturated',prepMinutes:30,specialHours:'Alta demanda',autoSaturationEnabled:false,autoSaturationLimit:5}});
  const temporaryProduct=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Producto temporal',price:35}}),temporarilyUnavailable=await api('/api/restaurant/products/'+temporaryProduct.data.id,{token:restaurant,method:'PATCH',body:{status:'temporary',duration:'30'}});ok(temporarilyUnavailable.status===200&&temporarilyUnavailable.data.availabilityStatus==='temporary','restaurante marca un producto agotado durante 30 minutos');const hiddenTemporary=await api('/api/restaurants/'+restaurantId+'/menu');ok(!hiddenTemporary.data.products.some(p=>p.id===temporaryProduct.data.id),'cliente no puede comprar un producto agotado temporalmente');const availabilityDb=new Database(dbFile);availabilityDb.prepare("UPDATE products SET unavailable_until=datetime('now','-1 minute') WHERE id=?").run(temporaryProduct.data.id);availabilityDb.close();const restoredTemporary=await api('/api/restaurants/'+restaurantId+'/menu');ok(restoredTemporary.data.products.some(p=>p.id===temporaryProduct.data.id),'producto temporal vuelve a estar disponible al vencer el plazo');
  const orderBase=()=>({restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()});
  const favoriteAdded=await api('/api/favorites/'+restaurantId,{token:customer.data.token,method:'PUT'}),favorites=await api('/api/favorites',{token:customer.data.token}),favoriteRemoved=await api('/api/favorites/'+restaurantId,{token:customer.data.token,method:'DELETE'});ok(favoriteAdded.status===200&&favorites.data.some(r=>r.id===restaurantId)&&favoriteRemoved.data.favorite===false,'cliente agrega, consulta y elimina restaurantes favoritos');
  const promotionCreated=await api('/api/restaurant/promotions',{token:restaurant,method:'POST',body:{title:'Platillo local de prueba',description:'Oferta exclusiva para comprobar la fase cinco'}}),publicPromotions=await api('/api/promotions'),employeePromotionDenied=await api('/api/restaurant/promotions',{token:employee,method:'POST',body:{title:'No autorizada',description:'No debe publicarse'}});ok(promotionCreated.status===201&&publicPromotions.data.some(p=>p.id===promotionCreated.data.id)&&employeePromotionDenied.status===403,'restaurante publica oferta local y respeta permisos');
  const couponCreated=await api('/api/admin/coupons',{token:admin,method:'POST',body:{code:'SAYULA10',description:'Diez por ciento de prueba',discountType:'percent',discountValue:10,minimumOrder:50,maximumDiscount:20,totalLimit:5,perUserLimit:1}}),couponDuplicate=await api('/api/admin/coupons',{token:admin,method:'POST',body:{code:'SAYULA10',discountType:'fixed',discountValue:5}}),couponQuote=await api('/api/growth/quote',{token:customer.data.token,method:'POST',body:{restaurantId,subtotal:100,deliveryFee:35,couponCode:'sayula10',useCredits:false}});ok(couponCreated.status===201&&couponDuplicate.status===409&&couponQuote.status===200&&couponQuote.data.couponDiscount===10&&couponQuote.data.total===125,'cupón valida código único, compra mínima y descuento desde servidor');
  const couponOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),couponCode:'SAYULA10'}});ok(couponOrder.status===201&&couponOrder.data.discount===10&&couponOrder.data.total===125,'pedido aplica cupón únicamente con cálculo del servidor');const couponLimit=await api('/api/growth/quote',{token:customer.data.token,method:'POST',body:{restaurantId,subtotal:100,deliveryFee:35,couponCode:'SAYULA10'}});ok(couponLimit.status===409,'límite por cliente evita reutilizar cupón');const couponCancelled=await api('/api/orders/'+couponOrder.data.orderId+'/cancel',{token:customer.data.token,method:'POST',body:{reason:'Comprobar devolución del beneficio'}}),couponReleased=await api('/api/growth/quote',{token:customer.data.token,method:'POST',body:{restaurantId,subtotal:100,deliveryFee:35,couponCode:'SAYULA10'}});ok(couponCancelled.status===200&&couponReleased.status===200,'cancelación libera el cupón de forma idempotente');
  const growthInitial=await api('/api/growth/me',{token:customer.data.token}),selfReferral=await api('/api/referrals/claim',{token:customer.data.token,method:'POST',body:{code:growthInitial.data.referralCode}});ok(growthInitial.status===200&&growthInitial.data.creditBalance===0&&selfReferral.status===400,'cliente consulta fidelidad y no puede autorreferirse');
  const invited=await api('/api/auth/register',{method:'POST',body:{name:'Cliente Invitado',email:'invitado@test.local',password:'Invitado-Seguro-12',termsAccepted:true}}),referralClaim=await api('/api/referrals/claim',{token:invited.data.token,method:'POST',body:{code:growthInitial.data.referralCode}}),referralRepeat=await api('/api/referrals/claim',{token:invited.data.token,method:'POST',body:{code:growthInitial.data.referralCode}});ok(invited.status===201&&referralClaim.status===201&&referralRepeat.status===409,'referido se registra una sola vez antes del primer pedido');
  const onlineOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),paymentMethod:'Mercado Pago'}});ok(onlineOrder.status===201&&onlineOrder.data.paymentStatus==='awaiting_online_payment'&&onlineOrder.data.checkoutUrl==='https://sandbox.mercadopago.test/checkout','pedido en línea crea checkout de prueba sin marcar pago');const preferenceRequest=paymentRequests.find(item=>item.method==='POST');ok(preferenceRequest?.authorization==='Bearer TEST-token-falso'&&preferenceRequest.idempotency==='come-sayula-order-'+onlineOrder.data.orderId&&preferenceRequest.body.external_reference==='order:'+onlineOrder.data.orderId&&preferenceRequest.body.items[0].unit_price===onlineOrder.data.total,'preferencia usa autorización, idempotencia, referencia y total exactos');const hiddenOnline=await api('/api/restaurant/me',{token:restaurant});ok(!hiddenOnline.data.orders.some(order=>order.id===onlineOrder.data.orderId),'restaurante no ve pedido mientras el pago está pendiente');const confirmedOnline=await api('/api/payments/mercadopago/confirm',{token:customer.data.token,method:'POST',body:{orderId:onlineOrder.data.orderId,paymentId:'pay-test-1'}});ok(confirmedOnline.status===200&&confirmedOnline.data.status==='paid','servidor consulta y confirma el pago aprobado');const visibleOnline=await api('/api/restaurant/me',{token:restaurant});ok(visibleOnline.data.orders.some(order=>order.id===onlineOrder.data.orderId&&order.payment_status==='paid'),'restaurante recibe pedido solamente después del pago verificado');const repeatedOnline=await api('/api/payments/mercadopago/confirm',{token:customer.data.token,method:'POST',body:{orderId:onlineOrder.data.orderId,paymentId:'pay-test-1'}});ok(repeatedOnline.status===200&&repeatedOnline.data.repeated===true,'confirmación repetida es idempotente');const invalidWebhook=await fetch(base+'/api/payments/mercadopago/webhook?data.id=pay-test-1',{method:'POST',headers:{'Content-Type':'application/json','x-request-id':'request-test','x-signature':'ts=1,v1=00'},body:JSON.stringify({type:'payment',data:{id:'pay-test-1'}})});ok(invalidWebhook.status===401,'webhook rechaza una firma inválida');
  const cardRejected=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),cardNumber:'NO-GUARDAR',securityCode:'XXX'}});ok(cardRejected.status===400,'pedidos rechazan datos sensibles de tarjeta');
  const auditDenied=await api('/api/admin/audit',{token:customer.data.token}),auditAllowed=await api('/api/admin/audit?limit=100',{token:admin});ok(auditDenied.status===403&&auditAllowed.status===200&&auditAllowed.data.some(entry=>entry.action==='password_reset_completed'),'auditoría reciente sólo está disponible para administración');
  const substitute=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Sustituto controlado',price:130}}),substitutionOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),address:'Pedido con sustitución'}}),substitutionPanel=await api('/api/restaurant/me',{token:restaurant}),substitutionItem=substitutionPanel.data.orders.find(order=>order.id===substitutionOrder.data.orderId).items[0],invalidPrep=await api('/api/restaurant/orders/'+substitutionOrder.data.orderId,{token:restaurant,method:'PATCH',body:{status:'accepted',prepMinutes:2}});ok(invalidPrep.status===400,'servidor rechaza un tiempo de preparación fuera del límite');const proposedSubstitution=await api('/api/restaurant/orders/'+substitutionOrder.data.orderId+'/substitutions',{token:restaurant,method:'POST',body:{originalItemId:substitutionItem.id,replacementProductId:substitute.data.id,description:'Alternativa disponible'}});ok(proposedSubstitution.status===201&&proposedSubstitution.data.difference===30,'restaurante propone sustitución con diferencia exacta');const beforeSubstitution=await api('/api/orders/my',{token:customer.data.token}),pendingSubstitution=await api('/api/orders/'+substitutionOrder.data.orderId+'/tracking',{token:customer.data.token});ok(beforeSubstitution.data.find(order=>order.id===substitutionOrder.data.orderId).total===135&&pendingSubstitution.data.substitutions[0].status==='pending','propuesta no modifica el total antes de autorización');const acceptedSubstitution=await api('/api/orders/'+substitutionOrder.data.orderId+'/substitutions/'+proposedSubstitution.data.id+'/respond',{token:customer.data.token,method:'POST',body:{accept:true}}),afterSubstitution=await api('/api/orders/my',{token:customer.data.token});ok(acceptedSubstitution.status===200&&afterSubstitution.data.find(order=>order.id===substitutionOrder.data.orderId).total===165,'aceptación expresa aplica sustitución y diferencia al total');const acceptedWithPrep=await api('/api/restaurant/orders/'+substitutionOrder.data.orderId,{token:restaurant,method:'PATCH',body:{status:'accepted',prepMinutes:25}});ok(acceptedWithPrep.status===200&&acceptedWithPrep.data.acceptedPrepMinutes===25&&acceptedWithPrep.data.acceptedEtaAt,'restaurante confirma minutos y ETA al aceptar');const isolateSubstitutionDb=new Database(dbFile);isolateSubstitutionDb.prepare('UPDATE orders SET is_demo=1 WHERE id=?').run(substitutionOrder.data.orderId);isolateSubstitutionDb.close();
  for(const test of [
    {name:'fecha programada inválida',body:{orderTiming:'scheduled',scheduledFor:'no-es-fecha'}},
    {name:'fecha programada pasada',body:{orderTiming:'scheduled',scheduledFor:new Date(Date.now()-60*60*1000).toISOString()}},
    {name:'menos de 45 minutos de anticipación',body:{orderTiming:'scheduled',scheduledFor:new Date(Date.now()+44*60*1000).toISOString()}},
    {name:'más de siete días de anticipación',body:{orderTiming:'scheduled',scheduledFor:new Date(Date.now()+7*24*60*60*1000+60*1000).toISOString()}}
  ]){const rejected=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),...test.body}});ok(rejected.status===400,'servidor rechaza '+test.name)}
  const sayulaTarget=new Date(Date.now()+46*60*1000),sayulaLocal=new Date(sayulaTarget.getTime()-6*60*60*1000).toISOString().slice(0,19)+'-06:00',sayulaScheduled=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),orderTiming:'scheduled',scheduledFor:sayulaLocal}});ok(sayulaScheduled.status===201&&Math.abs(new Date(sayulaScheduled.data.scheduledFor)-sayulaTarget)<1000,'servidor normaliza correctamente una hora explícita de Sayula');
  const longPrep=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'saturated',prepMinutes:100,specialHours:'Preparación larga de prueba'}});ok(longPrep.status===200&&longPrep.data.estimatedPrepMinutes===120,'tiempo operativo incluye preparación configurada y saturación');
  const requestedDate=new Date(Date.now()+100*60*1000),scheduled=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),orderTiming:'scheduled',scheduledFor:requestedDate.toISOString()}});ok(scheduled.status===201&&scheduled.data.orderTiming==='scheduled','pedido programado válido creado');ok(Math.abs(new Date(scheduled.data.scheduledFor).getTime()-requestedDate.getTime())<1000,'servidor guarda la fecha programada normalizada');
  const acceptedScheduled=await api('/api/restaurant/orders/'+scheduled.data.orderId,{token:restaurant,method:'PATCH',body:{status:'accepted'}});ok(acceptedScheduled.status===200,'restaurante acepta el pedido programado');const preparingScheduled=await api('/api/restaurant/orders/'+scheduled.data.orderId,{token:restaurant,method:'PATCH',body:{status:'preparing'}});ok(preparingScheduled.status===200,'preparación se habilita según el tiempo configurado');const earlyReady=await api('/api/restaurant/orders/'+scheduled.data.orderId,{token:restaurant,method:'PATCH',body:{status:'ready'}});ok(earlyReady.status===409,'pedido programado no puede marcarse listo demasiado pronto');
  const scheduledNotices=await api('/api/notifications',{token:restaurant});ok(scheduledNotices.data.notifications.some(n=>n.order_id===scheduled.data.orderId&&n.type==='scheduled_prep_reminder'),'restaurante recibe recordatorio al entrar en la ventana de preparación');
  const scheduledAdmin=await api('/api/admin/scheduled-orders',{token:admin});ok(scheduledAdmin.status===200&&scheduledAdmin.data.summary.upcoming===2&&scheduledAdmin.data.orders.every(order=>order.prep_start_at),'administrador consulta próximos y hora de preparación');
  const fixtureDb=new Database(dbFile);fixtureDb.prepare("UPDATE orders SET status='ready' WHERE id=?").run(scheduled.data.orderId);fixtureDb.close();
  const alcoholDeliveryDenied=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:alcohol.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID(),ageConfirmed:false}});ok(alcoholDeliveryDenied.status===403,'pedido a domicilio con alcohol exige confirmación de mayoría de edad');
  const cancelledOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Pedido que será cancelado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});const cancelled=await api('/api/restaurant/orders/'+cancelledOrder.data.orderId,{token:restaurant,method:'PATCH',body:{status:'cancelled'}});ok(cancelled.status===200,'restaurante cancela un pedido antes de prepararlo');
  const cancellableProduct=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Pieza cancelable',price:60,stockEnabled:true,stockQuantity:1,lowStockThreshold:1}}),customerCancellable=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:cancellableProduct.data.id,quantity:1}],address:'Pedido cancelable',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}}),cancelledByCustomer=await api('/api/orders/'+customerCancellable.data.orderId+'/cancel',{token:customer.data.token,method:'POST',body:{reason:'Me equivoqué al elegir'}});ok(cancelledByCustomer.status===200,'cliente cancela libremente antes de aceptación');const reorderedAfterCancel=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:cancellableProduct.data.id,quantity:1}],address:'Pedido después de cancelar',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(reorderedAfterCancel.status===201,'cancelación devuelve la existencia de forma atómica');const acceptedAfterCancel=await api('/api/restaurant/orders/'+reorderedAfterCancel.data.orderId,{token:restaurant,method:'PATCH',body:{status:'accepted'}}),lateCustomerCancel=await api('/api/orders/'+reorderedAfterCancel.data.orderId+'/cancel',{token:customer.data.token,method:'POST',body:{reason:'Intento tardío'}});ok(acceptedAfterCancel.status===200&&lateCustomerCancel.status===409,'cliente no puede cancelar directamente después de aceptación');const isolateCancellationDb=new Database(dbFile);isolateCancellationDb.prepare('UPDATE orders SET is_demo=1 WHERE id IN (?,?)').run(customerCancellable.data.orderId,reorderedAfterCancel.data.orderId);isolateCancellationDb.close();
  const unansweredOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),address:'Pedido sin respuesta de prueba'}}),noticeDb=new Database(dbFile);noticeDb.prepare("UPDATE orders SET created_at=datetime('now','-20 minutes') WHERE id=?").run(unansweredOrder.data.orderId);noticeDb.close();await wait(300);const unansweredCustomer=await api('/api/notifications',{token:customer.data.token}),unansweredRestaurant=await api('/api/notifications',{token:restaurant}),unansweredAdmin=await api('/api/notifications',{token:admin});ok([unansweredCustomer,unansweredRestaurant,unansweredAdmin].every(result=>result.data.notifications.some(n=>n.order_id===unansweredOrder.data.orderId&&n.type==='order_unanswered')),'cliente, restaurante y administrador reciben alerta de pedido sin respuesta');
  const limited=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Última pieza',price:55,stockEnabled:true,stockQuantity:1,lowStockThreshold:1}}),limitedBody=()=>({restaurantId,items:[{productId:limited.data.id,quantity:1}],address:'Prueba de inventario',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}),stockRace=await Promise.all([api('/api/orders',{token:customer.data.token,method:'POST',body:limitedBody()}),api('/api/orders',{token:customer.data.token,method:'POST',body:limitedBody()})]);ok(stockRace.filter(result=>result.status===201).length===1&&stockRace.filter(result=>result.status===409).length===1,'inventario simultáneo permite vender únicamente la existencia disponible');
  const configurable=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Producto configurable',price:80,variants:[{name:'Grande',priceDelta:20}],addons:[{name:'Queso',priceDelta:10}]}}),configuredOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:configurable.data.id,quantity:1,variant:'Grande',addons:['Queso']}],address:'Prueba de repetición',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});await api('/api/restaurant/products/'+configurable.data.id,{token:restaurant,method:'PUT',body:{name:'Producto configurable',description:'Actualizado',image:'',category:'Comida',price:90,stockEnabled:false,variants:[{name:'Grande',priceDelta:30}],addons:[{name:'Salsa',priceDelta:5}]}});const changedRepeat=await api('/api/orders/'+configuredOrder.data.orderId+'/repeat',{token:customer.data.token});ok(changedRepeat.status===200&&changedRepeat.data.items[0].price===120&&changedRepeat.data.items[0].addons.length===0&&changedRepeat.data.warnings.some(message=>message.includes('complementos')),'repetición usa precio actual y advierte complementos retirados');await api('/api/restaurant/products/'+configurable.data.id,{token:restaurant,method:'PATCH',body:{available:false}});const unavailableRepeat=await api('/api/orders/'+configuredOrder.data.orderId+'/repeat',{token:customer.data.token});ok(unavailableRepeat.status===409,'repetición rechaza un pedido cuyos productos quedaron agotados');
  const goalStart=new Date(Date.now()-60*1000).toISOString(),goalEnd=new Date(Date.now()+24*60*60*1000).toISOString(),invalidGoal=await api('/api/admin/driver-goals',{token:admin,method:'POST',body:{name:'Meta inválida',periodType:'daily',targetDeliveries:0,bonusAmount:50,startsAt:goalStart,endsAt:goalEnd}}),goalCreated=await api('/api/admin/driver-goals',{token:admin,method:'POST',body:{name:'Primera entrega del día',periodType:'daily',targetDeliveries:1,bonusAmount:50,startsAt:goalStart,endsAt:goalEnd}}),goalDenied=await api('/api/admin/driver-goals',{token:d1,method:'POST',body:{name:'Sin permiso',periodType:'daily',targetDeliveries:1,bonusAmount:50,startsAt:goalStart,endsAt:goalEnd}});ok(invalidGoal.status===400&&goalCreated.status===201&&goalDenied.status===403,'administración crea metas válidas y protege permisos');
  const orders=[];
  for(const paymentMethod of ['Efectivo','Transferencia','Tarjeta al recibir']){const created=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod,orderTiming:'immediate',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(created.status===201&&created.data.orderTiming==='immediate'&&created.data.scheduledFor===null,'pedido inmediato creado con '+paymentMethod);ok(created.data.paymentStatus===(paymentMethod==='Transferencia'?'awaiting_confirmation':'pay_on_delivery'),'estado de pago correcto para '+paymentMethod);orders.push({id:created.data.orderId,paymentMethod});if(paymentMethod==='Transferencia'){const paid=await api('/api/restaurant/orders/'+created.data.orderId+'/payment',{token:restaurant,method:'PATCH',body:{}});ok(paid.status===200&&paid.data.paymentStatus==='confirmed','transferencia conciliada manualmente')}for(const status of ['accepted','preparing','ready']){const actor=status==='accepted'&&paymentMethod==='Efectivo'?employee:restaurant;const moved=await api('/api/restaurant/orders/'+created.data.orderId,{token:actor,method:'PATCH',body:{status}});ok(moved.status===200,'pedido '+created.data.orderId+' cambia a '+status)}}
  const backwards=await api('/api/restaurant/orders/'+orders[0].id,{token:restaurant,method:'PATCH',body:{status:'accepted'}}),stillReady=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token});ok(backwards.status===400&&stillReady.data.status==='ready','un pedido nunca puede retroceder de estado');
  await Promise.all([api('/api/delivery/location',{token:d1,method:'PUT',body:{latitude:19.88,longitude:-103.60,accuracy:5}}),api('/api/delivery/location',{token:d2,method:'PUT',body:{latitude:19.881,longitude:-103.60,accuracy:5}})]);
  const earlyAvailable=await api('/api/delivery/orders/available',{token:d1});ok(!earlyAvailable.data.orders.some(order=>order.id===scheduled.data.orderId),'pedido programado no se ofrece al repartidor con demasiada anticipación');const offered=earlyAvailable.data.orders.find(order=>order.id===orders[0].id);ok(offered&&!('address' in offered)&&!('customer_name' in offered)&&!('customer_phone' in offered)&&!('delivery_latitude' in offered),'repartidor no recibe datos privados antes de aceptar');
  const earlyAccept=await api('/api/delivery/orders/'+scheduled.data.orderId+'/accept',{token:d1,method:'POST'});ok(earlyAccept.status===409,'API bloquea aceptación anticipada del pedido programado');
  const customerNotices=await api('/api/notifications',{token:customer.data.token});ok(customerNotices.status===200&&customerNotices.data.notifications.some(n=>n.type==='order_ready'),'cliente recibe avisos persistentes del avance');
  const employeeNotices=await api('/api/notifications',{token:employee});ok(employeeNotices.status===200&&employeeNotices.data.notifications.some(n=>n.type==='order_received'),'empleado autorizado recibe aviso de pedido nuevo');
  const readNotices=await api('/api/notifications/read',{token:customer.data.token,method:'PATCH',body:{}});const afterRead=await api('/api/notifications',{token:customer.data.token});ok(readNotices.status===200&&afterRead.data.unread===0,'usuario puede marcar sus avisos como leídos');
  const race=await Promise.all([api('/api/delivery/orders/'+orders[0].id+'/accept',{token:d1,method:'POST'}),api('/api/delivery/orders/'+orders[0].id+'/accept',{token:d2,method:'POST'})]);ok(race.filter(r=>r.status===200).length===1&&race.filter(r=>r.status===409).length===1,'sólo un repartidor gana la aceptación concurrente');
  const pinDb=new Database(dbFile,{readonly:true}),protectedPin=pinDb.prepare('SELECT delivery_pin_hash,delivery_pin_cipher FROM orders WHERE id=?').get(orders[0].id);pinDb.close();ok(/^[a-f0-9]{64}$/.test(protectedPin.delivery_pin_hash)&&protectedPin.delivery_pin_cipher&&!protectedPin.delivery_pin_cipher.includes('delivery_pin'),'PIN de entrega se guarda con hash y cifrado, nunca como texto directo');
  const winner=race[0].status===200?d1:d2,started=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:'delivering'}});ok(started.status===200,'entrega avanza a delivering');const shared=await api('/api/delivery/orders/'+orders[0].id+'/location',{token:winner,method:'PATCH',body:{latitude:19.885,longitude:-103.601,accuracy:5}});ok(shared.status===200,'repartidor comparte ubicación durante entrega');const deliveryTracking=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token}),badPin=deliveryTracking.data.delivery_pin==='0000'?'0001':'0000',missingPin=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:'delivered'}}),wrongPin=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:'delivered',deliveryPin:badPin}}),beforePin=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token});ok(missingPin.status===403&&wrongPin.status===403&&beforePin.data.status==='delivering','PIN correcto es obligatorio y los intentos fallidos no cierran el pedido');const delivered=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:'delivered',deliveryPin:beforePin.data.delivery_pin}});ok(delivered.status===200,'entrega avanza a delivered con el PIN correcto');const incentives=await api('/api/delivery/incentives',{token:winner}),incentivesDenied=await api('/api/delivery/incentives',{token:customer.data.token});ok(incentives.status===200&&incentivesDenied.status===403&&incentives.data.goals.some(g=>g.id===goalCreated.data.id&&g.progress===1&&g.completed_at)&&incentives.data.streak.current_days===1&&incentives.data.summary.pending===50,'entrega válida completa meta, actualiza racha y genera bono pendiente');const adminIncentives=await api('/api/admin/driver-incentives',{token:admin}),earnedReward=adminIncentives.data.rewards.find(w=>w.goal_id===goalCreated.data.id&&w.status==='earned'),invalidPay=await api('/api/admin/driver-rewards/'+earnedReward.id+'/pay',{token:admin,method:'PATCH',body:{reference:'x'}}),paidReward=await api('/api/admin/driver-rewards/'+earnedReward.id+'/pay',{token:admin,method:'PATCH',body:{reference:'BONO-PRUEBA-001'}}),duplicatePay=await api('/api/admin/driver-rewards/'+earnedReward.id+'/pay',{token:admin,method:'PATCH',body:{reference:'BONO-PRUEBA-002'}});ok(invalidPay.status===400&&paidReward.status===200&&duplicatePay.status===409,'bono requiere referencia y no puede pagarse dos veces');const manualBonus=await api('/api/admin/driver-bonuses',{token:admin,method:'POST',body:{deliveryUserId:earnedReward.delivery_user_id,amount:25,reason:'Reconocimiento de prueba'}}),afterBonus=await api('/api/delivery/incentives',{token:winner});ok(manualBonus.status===201&&afterBonus.data.summary.pending===25&&afterBonus.data.summary.paid===50&&afterBonus.data.level.name==='Inicio','bono especial y nivel del repartidor permanecen separados del efectivo');
  for(let i=1;i<orders.length;i++){const courier=i%2?d1:d2;const accepted=await api('/api/delivery/orders/'+orders[i].id+'/accept',{token:courier,method:'POST'});ok(accepted.status===200,'repartidor acepta pedido con '+orders[i].paymentMethod);for(const state of ['delivering','delivered']){const tracking=await api('/api/orders/'+orders[i].id+'/tracking',{token:customer.data.token});const moved=await api('/api/delivery/orders/'+orders[i].id,{token:courier,method:'PATCH',body:{status:state,deliveryPin:tracking.data.delivery_pin}});ok(moved.status===200,'flujo '+orders[i].paymentMethod+' termina en '+state)}}
  const growthAfterDelivery=await api('/api/growth/me',{token:customer.data.token});ok(growthAfterDelivery.data.loyalty.points>0&&growthAfterDelivery.data.loyalty.lifetime_points===growthAfterDelivery.data.loyalty.points,'entregas válidas generan puntos de fidelidad');const compensation=await api('/api/admin/compensations',{token:admin,method:'POST',body:{customerId:customer.data.user.id,orderId:orders[0].id,amount:50,reason:'Compensación controlada de prueba'}}),duplicateCompensation=await api('/api/admin/compensations',{token:admin,method:'POST',body:{customerId:customer.data.user.id,orderId:orders[0].id,amount:50,reason:'Intento duplicado'}}),growthWithCredit=await api('/api/growth/me',{token:customer.data.token});ok(compensation.status===201&&duplicateCompensation.status===409&&growthWithCredit.data.creditBalance===50,'compensación exige pedido cerrado y evita duplicados');const creditOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),useCredits:true}});ok(creditOrder.status===201&&creditOrder.data.creditUsed===50&&creditOrder.data.total===85,'cliente aplica crédito promocional sin convertirlo en dinero');const creditCancelled=await api('/api/orders/'+creditOrder.data.orderId+'/cancel',{token:customer.data.token,method:'POST',body:{reason:'Comprobar devolución de crédito'}}),growthRestored=await api('/api/growth/me',{token:customer.data.token});ok(creditCancelled.status===200&&growthRestored.data.creditBalance===50,'cancelación devuelve el crédito exactamente una vez');
  const noContact=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),address:'Entrega sin contacto',deliveryMethod:'no_contact'}});for(const status of ['accepted','preparing','ready'])await api('/api/restaurant/orders/'+noContact.data.orderId,{token:restaurant,method:'PATCH',body:{status}});await api('/api/delivery/location',{token:d1,method:'PUT',body:{latitude:19.88,longitude:-103.60,accuracy:5}});const noContactAccepted=await api('/api/delivery/orders/'+noContact.data.orderId+'/accept',{token:d1,method:'POST'}),noContactStarted=await api('/api/delivery/orders/'+noContact.data.orderId,{token:d1,method:'PATCH',body:{status:'delivering'}}),missingPhoto=await api('/api/delivery/orders/'+noContact.data.orderId,{token:d1,method:'PATCH',body:{status:'delivered'}}),noContactDelivered=await api('/api/delivery/orders/'+noContact.data.orderId,{token:d1,method:'PATCH',body:{status:'delivered',proofDataUrl:sampleImage,latitude:19.89,longitude:-103.60}});ok(noContactAccepted.status===200&&noContactStarted.status===200&&missingPhoto.status===400&&noContactDelivered.status===200,'entrega sin contacto exige y guarda una fotografía válida');const noContactTracking=await api('/api/orders/'+noContact.data.orderId+'/tracking',{token:customer.data.token}),proofCustomer=await api('/api/orders/'+noContact.data.orderId+'/delivery-proof',{token:customer.data.token}),proofOtherCourier=await api('/api/orders/'+noContact.data.orderId+'/delivery-proof',{token:d2});ok(noContactTracking.data.delivery_proof_available===true&&proofCustomer.status===200&&proofOtherCourier.status===403,'evidencia se muestra al cliente y permanece privada para terceros');const isolateProofDb=new Database(dbFile);isolateProofDb.prepare('UPDATE orders SET is_demo=1 WHERE id=?').run(noContact.data.orderId);isolateProofDb.close();
  const closedTracking=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token});ok(closedTracking.status===200&&closedTracking.data.latitude===null&&closedTracking.data.longitude===null&&closedTracking.data.delivery_phone===null,'seguimiento oculta ubicación y teléfono después de entregar');
  const finalCustomerNotices=await api('/api/notifications',{token:customer.data.token}),customerTypes=new Set(finalCustomerNotices.data.notifications.filter(n=>n.order_id===orders[0].id).map(n=>n.type));for(const type of ['order_accepted','order_preparing','order_ready','order_assigned','order_delivering','order_delivered'])ok(customerTypes.has(type),'cliente recibe aviso '+type);
  const finalRestaurantNotices=await api('/api/notifications',{token:restaurant}),restaurantTypes=new Set(finalRestaurantNotices.data.notifications.filter(n=>n.order_id===orders[0].id).map(n=>n.type));for(const type of ['order_assigned','order_delivering','order_delivered'])ok(restaurantTypes.has(type),'restaurante recibe aviso '+type);
  const repeatOrder=await api('/api/orders/'+orders[0].id+'/repeat',{token:customer.data.token});ok(repeatOrder.status===200&&repeatOrder.data.items.length>0&&repeatOrder.data.items[0].restaurantId===restaurantId,'cliente puede repetir un pedido con precios y disponibilidad actuales');
  const closedRestaurantView=await api('/api/restaurant/me',{token:restaurant});const closedOrder=closedRestaurantView.data.orders.find(item=>item.id===orders[0].id);ok(closedOrder?.customer_phone===null&&closedOrder?.delivery_latitude===null&&closedOrder?.address==='Datos ocultos al cerrar el pedido','restaurante deja de ver datos personales al cerrar el pedido');
  const review=await api('/api/orders/'+orders[0].id+'/review',{token:customer.data.token,method:'POST',body:{restaurantRating:5,deliveryRating:4,tipAmount:20,comment:'Entrega controlada'}});ok(review.status===201&&review.data.tipAmount===20&&review.data.tipMethod==='cash','cliente califica y registra propina en efectivo');
  const duplicateReview=await api('/api/orders/'+orders[0].id+'/review',{token:customer.data.token,method:'POST',body:{restaurantRating:5,tipAmount:0}});ok(duplicateReview.status===409,'un pedido no puede calificarse dos veces');
  const courierHistory=await api('/api/delivery/orders/my',{token:winner}),closedCourierOrder=courierHistory.data.find(item=>item.id===orders[0].id);ok(closedCourierOrder?.tip_amount===20,'repartidor ve la propina registrada');ok(closedCourierOrder?.customer_phone===null&&closedCourierOrder?.delivery_latitude===null&&closedCourierOrder?.address==='Datos ocultos al cerrar la entrega','repartidor deja de ver datos personales al cerrar la entrega');
  const cashAccountDenied=await api('/api/delivery/cash-account',{token:customer.data.token}),cashAccount=await api('/api/delivery/cash-account',{token:winner});ok(cashAccountDenied.status===403&&cashAccount.status===200&&cashAccount.data.pending.cash_collected===135&&cashAccount.data.pending.courier_earnings===35&&cashAccount.data.pending.amount_to_remit===100,'libro de efectivo calcula desde servidor cobro, ganancia y saldo sin exponerlo a otros roles');const cashReport=await api('/api/delivery/cash-settlements',{token:winner,method:'POST',body:{reportedAmount:99,note:'Falta un peso por revisar'}}),duplicateCashReport=await api('/api/delivery/cash-settlements',{token:winner,method:'POST',body:{reportedAmount:100}});ok(cashReport.status===201&&cashReport.data.expectedAmount===100&&cashReport.data.differenceAmount===-1&&duplicateCashReport.status===409,'diferencia de efectivo abre una sola revisión sin duplicar reportes');const adminCashReports=await api('/api/admin/courier-cash-settlements',{token:admin}),reportedCash=adminCashReports.data.find(item=>item.id===cashReport.data.id);ok(reportedCash?.status==='review'&&reportedCash?.orders_count===1,'administración consulta el reporte y los pedidos incluidos');const invalidCashClose=await api('/api/admin/courier-cash-settlements/'+cashReport.data.id,{token:admin,method:'PATCH',body:{reference:'x',adminNote:'x'}}),cashClosedByAdmin=await api('/api/admin/courier-cash-settlements/'+cashReport.data.id,{token:admin,method:'PATCH',body:{reference:'CAJA-PRUEBA-001',adminNote:'Diferencia revisada y documentada'}}),cashAccountClosed=await api('/api/delivery/cash-account',{token:winner});ok(invalidCashClose.status===400&&cashClosedByAdmin.status===200&&cashAccountClosed.data.pending.amount_to_remit===0&&cashAccountClosed.data.settlements[0].status==='settled','administración cierra la conciliación con referencia, nota y auditoría');
  const ratedRestaurants=await api('/api/restaurants');ok(ratedRestaurants.data.find(item=>item.id===restaurantId)?.rating===5,'calificación actualiza reputación del restaurante');
  const feedbackBody={category:'error',rating:3,answers:['Sí','Sí','No','Avisos más claros'],comment:'La pantalla del pedido tardó en actualizar',orderId:orders[0].id,anonymous:true,contactAllowed:true};
  const feedback=await api('/api/feedback',{token:customer.data.token,method:'POST',body:feedbackBody});ok(feedback.status===201&&/^[a-f0-9]{24}$/.test(feedback.data.trackingCode),'cliente envía opinión anónima y recibe folio privado');
  const feedbackStatus=await api('/api/feedback/status/'+feedback.data.trackingCode);ok(feedbackStatus.status===200&&feedbackStatus.data.status==='received','folio permite consultar estado de opinión');
  const repeated=await api('/api/feedback',{token:customer.data.token,method:'POST',body:{...feedbackBody,orderId:orders[1].id}});ok(repeated.status===201,'se acepta un segundo reporte del mismo problema');
  const adminFeedback=await api('/api/admin/feedback',{token:admin});const reported=adminFeedback.data.find(item=>item.id===feedback.data.id);ok(adminFeedback.status===200&&reported?.frequency===2&&reported.user_id===null&&reported.contact_email===null,'panel agrupa reportes repetidos y protege el anonimato');
  const feedbackUpdate=await api('/api/admin/feedback/'+feedback.data.id,{token:admin,method:'PATCH',body:{status:'reviewing',severity:'high',adminNotes:'Revisar actualización del seguimiento'}});ok(feedbackUpdate.status===200&&feedbackUpdate.data.severity==='high','administrador clasifica gravedad y avance');
  const updatedFeedbackStatus=await api('/api/feedback/status/'+feedback.data.trackingCode);ok(updatedFeedbackStatus.data.status==='reviewing'&&updatedFeedbackStatus.data.severity==='high','usuario consulta el avance actualizado');
  const issue=await api('/api/order-issues',{token:customer.data.token,method:'POST',body:{orderId:orders[0].id,issueType:'missing_product',description:'Faltó una bebida en la prueba'}});ok(issue.status===201,'cliente reporta problema relacionado con su pedido');
  const issuesAdmin=await api('/api/admin/order-issues',{token:admin});ok(issuesAdmin.data.some(item=>item.id===issue.data.id),'administrador ve el problema reportado');
  const issueUpdated=await api('/api/admin/order-issues/'+issue.data.id+'/resolve',{token:admin,method:'POST',body:{responsibility:'restaurant',resolution:'Restaurante confirmó el faltante y acordó solución'}});ok(issueUpdated.status===200&&issueUpdated.data.responsibility==='restaurant','administrador resuelve la disputa y documenta responsabilidad');
  const trustBeforeAdjustment=await api('/api/trust/me',{token:customer.data.token}),trustAdjusted=await api('/api/admin/trust/'+customer.data.user.id,{token:admin,method:'PATCH',body:{delta:5,reason:'Historial positivo revisado manualmente'}}),trustAfterAdjustment=await api('/api/trust/me',{token:customer.data.token});ok(trustAdjusted.status===200&&trustAfterAdjustment.data.score===trustBeforeAdjustment.data.score+5,'confianza puede recuperarse con ajuste positivo, motivo y auditoría');
  const chatOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),address:'Pedido para chat privado'}});ok(chatOrder.status===201,'cliente crea pedido para conversación privada');
  const customerMessage=await api('/api/orders/'+chatOrder.data.orderId+'/messages',{token:customer.data.token,method:'POST',body:{channel:'customer_restaurant',message:'¿Podrían poner la salsa aparte?'}}),restaurantThread=await api('/api/orders/'+chatOrder.data.orderId+'/messages?channel=customer_restaurant',{token:restaurant}),courierDeniedChat=await api('/api/orders/'+chatOrder.data.orderId+'/messages?channel=customer_restaurant',{token:d1});ok(customerMessage.status===201&&restaurantThread.status===200&&restaurantThread.data.messages[0].message.includes('salsa')&&courierDeniedChat.status===403,'chat separa cliente, restaurante y repartidor por pedido');
  const privateDataBlocked=await api('/api/orders/'+chatOrder.data.orderId+'/messages',{token:restaurant,method:'POST',body:{channel:'customer_restaurant',message:'Escríbeme al 3411234567'}});ok(privateDataBlocked.status===400,'chat bloquea números y correos personales');
  const groupCreated=await api('/api/group-orders',{token:customer.data.token,method:'POST',body:{restaurantId}}),groupView=await api('/api/group-orders/'+groupCreated.data.code,{token:customer.data.token}),groupItem=await api('/api/group-orders/'+groupCreated.data.code+'/items',{token:customer.data.token,method:'POST',body:{productId:product.data.id,quantity:2,variant:'',addons:[]}}),groupCompleted=await api('/api/group-orders/'+groupCreated.data.code+'/complete',{token:customer.data.token,method:'POST'});ok(groupCreated.status===201&&groupView.status===200&&groupItem.status===201&&groupCompleted.status===200&&groupCompleted.data.items[0].quantity===2&&groupCompleted.data.items[0].price===100,'pedido grupal valida menú y entrega carrito actual al creador');
  const groupClosed=await api('/api/group-orders/'+groupCreated.data.code+'/items',{token:customer.data.token,method:'POST',body:{productId:product.data.id,quantity:1}});ok(groupClosed.status===409,'pedido grupal cerrado ya no acepta productos');
  const survey=await api('/api/orders/'+orders[0].id+'/survey',{token:customer.data.token,method:'POST',body:{everythingOk:false}}),surveyRepeated=await api('/api/orders/'+orders[0].id+'/survey',{token:customer.data.token,method:'POST',body:{everythingOk:true}}),helpTopics=await api('/api/help/topics');ok(survey.status===201&&survey.data.needsHelp&&survey.data.helpUrl.includes(String(orders[0].id))&&surveyRepeated.status===409&&helpTopics.status===200&&helpTopics.data.length>=5,'encuesta rápida deriva problemas y evita respuestas duplicadas');
  const closedChat=await api('/api/orders/'+orders[0].id+'/messages',{token:customer.data.token,method:'POST',body:{channel:'customer_restaurant',message:'Mensaje tardío'}});ok(closedChat.status===409,'chat se cierra al terminar el pedido');
  const demo=await api('/api/admin/demo/create',{token:admin,method:'POST',body:{}});ok(demo.status===201&&demo.data.status==='received','administrador crea pedido de demostración aislado');
  for(const expected of ['accepted','preparing','ready','assigned','delivering','delivered']){const advanced=await api('/api/admin/demo/'+demo.data.orderId+'/advance',{token:admin,method:'POST',body:{}});ok(advanced.status===200&&advanced.data.status===expected,'demostración avanza a '+expected)}
  const resetDemo=await api('/api/admin/demo',{token:admin,method:'DELETE'});ok(resetDemo.status===200&&resetDemo.data.removed===6,'reinicio elimina únicamente los pedidos aislados de demostración');
  const subscriptions=await api('/api/admin/subscriptions',{token:admin});const subscription=subscriptions.data.find(s=>s.restaurant_id===restaurantId);ok(subscription?.registration_fee===50&&subscription?.first_month_fee===100&&subscription?.initial_payment_total===150&&subscription?.promotion_monthly_fee===100&&subscription?.regular_monthly_fee===200,'inscripción y primera mensualidad quedan desglosadas');
  const registration=await api('/api/admin/subscriptions/'+restaurantId+'/payment',{token:admin,method:'PATCH',body:{acceptedTerms:true}});ok(registration.status===200&&registration.data.firstMonthIncluded,'inscripción confirmada incluye primera mensualidad');
  let settlement=await api('/api/restaurant/settlement',{token:restaurant});ok(settlement.status===200&&settlement.data.commissionPercent===5&&settlement.data.days[0]?.orders_count===3&&settlement.data.days[0]?.sales===300&&settlement.data.days[0]?.commission===15&&settlement.data.days[0]?.restaurant_due===285&&settlement.data.days[0]?.cancellations===4&&settlement.data.days[0]?.reversed_amount===480,'corte aplica 5% sólo a pedidos nuevos y conserva cancelaciones');
  const pendingSettlements=await api('/api/admin/settlements',{token:admin});const pendingCut=pendingSettlements.data.pending.find(c=>c.restaurant_id===restaurantId);ok(pendingCut?.amount===285,'administrador ve el saldo neto con comisión del 5%');
  const proof='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
  const paidCut=await api('/api/admin/settlements',{token:admin,method:'POST',body:{restaurantId,periodDate:pendingCut.period_date,reference:'TRX-PRUEBA-001',proofDataUrl:proof}});ok(paidCut.status===201&&paidCut.data.amount===285,'administrador registra fecha, referencia y comprobante del corte');
  settlement=await api('/api/restaurant/settlement',{token:restaurant});ok(settlement.data.days[0]?.pending_due===0&&settlement.data.days[0]?.paid_due===285&&settlement.data.batches[0]?.reference==='TRX-PRUEBA-001','restaurante consulta corte pagado e historial');
  const proofResponse=await fetch(base+'/api/settlements/'+paidCut.data.batchId+'/proof',{headers:{Authorization:'Bearer '+restaurant}});ok(proofResponse.status===200&&String(proofResponse.headers.get('content-type')).startsWith('image/'),'comprobante privado sólo se obtiene con sesión autorizada');
  const duplicateCut=await api('/api/admin/settlements',{token:admin,method:'POST',body:{restaurantId,periodDate:pendingCut.period_date,reference:'DUPLICADO'}});ok(duplicateCut.status===409,'un corte pagado no puede conciliarse dos veces');
  const history=await api('/api/orders/my',{token:customer.data.token});for(const order of orders){const saved=history.data.find(item=>item.id===order.id);ok(saved?.status==='delivered','pedido '+order.paymentMethod+' quedó entregado');ok(saved?.payment_status===(order.paymentMethod==='Transferencia'?'confirmed':'paid'),'pago final correcto para '+order.paymentMethod)}
  const savedScheduled=history.data.find(item=>item.id===scheduled.data.orderId);ok(savedScheduled?.order_timing==='scheduled'&&savedScheduled?.scheduled_for,'cliente recibe la fecha del pedido programado');const restaurantScheduled=(await api('/api/restaurant/me',{token:restaurant})).data.orders.find(item=>item.id===scheduled.data.orderId);ok(restaurantScheduled?.order_timing==='scheduled'&&restaurantScheduled?.scheduled_for,'restaurante recibe la fecha del pedido programado');
  const managedUsers=await api('/api/admin/users',{token:admin}),restaurantOwner=managedUsers.data.find(user=>user.email==='rest@test.local');await api('/api/admin/users/'+restaurantOwner.id+'/status',{token:admin,method:'PATCH',body:{status:'suspended'}});const staleDb=new Database(dbFile);staleDb.prepare('UPDATE restaurants SET active=1 WHERE id=?').run(restaurantId);staleDb.close();const suspendedDirectory=await api('/api/restaurants'),suspendedMenu=await api('/api/restaurants/'+restaurantId+'/menu'),suspendedHours=await api('/api/restaurants/'+restaurantId+'/business-hours'),suspendedQuote=await api('/api/delivery-quote',{token:customer.data.token,method:'POST',body:{restaurantId,deliveryLatitude:19.89,deliveryLongitude:-103.60}}),suspendedGroups=await api('/api/group-orders/restaurants',{token:customer.data.token});ok(!suspendedDirectory.data.some(item=>item.id===restaurantId),'cuenta suspendida queda fuera del directorio aunque conserve datos');ok(suspendedMenu.status===404,'cuenta suspendida no expone su menú');ok(suspendedHours.status===404,'cuenta suspendida no expone sus horarios');ok(suspendedQuote.status===404,'cuenta suspendida no permite cotizar entregas');ok(!suspendedGroups.data.some(item=>item.id===restaurantId),'cuenta suspendida queda fuera de pedidos grupales');await api('/api/admin/users/'+restaurantOwner.id+'/status',{token:admin,method:'PATCH',body:{status:'approved'}});
  console.log('\nTodas las pruebas controladas terminaron correctamente.');
}
run().catch(error=>{console.error('PRUEBA FALLIDA:',error.message);process.exitCode=1}).finally(()=>{child.kill();mailServer.close();paymentServer.close();setTimeout(()=>{for(const suffix of ['', '-wal','-shm'])try{fs.unlinkSync(dbFile+suffix)}catch(e){}},300)});
