const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),{spawn}=require('child_process'),crypto=require('crypto'),Database=require('better-sqlite3');
const root=__dirname,dbFile=path.join(os.tmpdir(),'test-come-sayula.db'),port=3199,mailPort=3200,base=`http://127.0.0.1:${port}`,mailRequests=[];
const mailServer=http.createServer((req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{mailRequests.push({url:req.url,authorization:req.headers.authorization,body:JSON.parse(body)});res.writeHead(202);res.end();});});
mailServer.listen(mailPort,'127.0.0.1');
for(const suffix of ['', '-wal','-shm'])try{fs.unlinkSync(dbFile+suffix)}catch(e){}
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,OPENAI_API_KEY:'',DATA_DIR:os.tmpdir(),DB_FILE:dbFile,PORT:String(port),ADMIN_EMAIL:'admin@test.local',ADMIN_PASSWORD:'Admin-Pruebas-2026',DISABLE_AUTOMATIC_BACKUP:'1',DEV_SHOW_RESET_TOKEN:'1',SENDGRID_API_KEY:'SG.test-only-not-a-secret',SENDGRID_FROM_EMAIL:'correo@test.local',SENDGRID_FROM_NAME:'COME SAYULA pruebas',SENDGRID_API_URL:`http://127.0.0.1:${mailPort}/v3/mail/send`,NOTIFICATION_WORKER_INTERVAL_MS:'100',ORDER_RATE_LIMIT_MAX:'100'},stdio:['ignore','pipe','pipe']});
let serverError='';child.stderr.on('data',chunk=>serverError+=chunk.toString());
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function api(url,{token,method='GET',body}={}){const response=await fetch(base+url,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});let data={};try{data=await response.json()}catch(e){}return {status:response.status,data,headers:response.headers};}
function ok(condition,message){if(!condition)throw new Error(message);console.log('✓ '+message)}
async function login(email,password,role){const r=await api('/api/auth/login',{method:'POST',body:{email,password,role}});ok(r.status===200,'inicio de sesión '+role);return r.data.token}
async function run(){
  for(let i=0;i<100;i++){await wait(150);try{if((await api('/api/health')).status===200)break}catch(e){}if(i===99)throw new Error('El servidor de prueba no inició: '+serverError.trim())}
  const healthHeaders=await api('/api/health');ok(healthHeaders.headers.get('cache-control')?.includes('no-store')&&healthHeaders.headers.get('x-content-type-options')==='nosniff'&&healthHeaders.headers.get('content-security-policy'),'API aplica encabezados de seguridad y evita caché sensible');
  const legalResponse=await fetch(base+'/legal.html'),legalText=await legalResponse.text();ok(legalResponse.status===200&&legalText.includes('Versión vigente: 8 de septiembre de 2026')&&legalText.includes('Solicitud ARCO')&&!legalText.includes('Documento previo a producción'),'aviso integral publica responsable, derechos y versión vigente sin texto pendiente');
  const weakPassword=await api('/api/auth/register',{method:'POST',body:{name:'Clave débil',email:'debil@test.local',password:'Corta-123',role:'customer',termsAccepted:true}});ok(weakPassword.status===400,'registro exige contraseña de al menos diez caracteres');
  const denied=await api('/api/auth/register',{method:'POST',body:{name:'Intruso',email:'staff-public@test.local',password:'Contrasena12',role:'delivery',termsAccepted:true}});ok(denied.status===403,'registro público bloquea roles operativos');
  const customer=await api('/api/auth/register',{method:'POST',body:{name:'Cliente Prueba',email:'cliente@test.local',phone:'3410000000',password:'Cliente-Prueba-12',role:'customer',termsAccepted:true}});ok(customer.status===201,'registro público permite clientes con consentimiento');
  const consentDb=new Database(dbFile,{readonly:true}),consent=consentDb.prepare("SELECT terms_version FROM users WHERE email='cliente@test.local'").get();consentDb.close();ok(consent?.terms_version==='2026-09-08','registro conserva la versión exacta de términos aceptada');
  const admin=await login('admin@test.local','Admin-Pruebas-2026','admin');
  const previousCustomerToken=customer.data.token,forgotten=await api('/api/auth/forgot-password',{method:'POST',body:{email:'cliente@test.local'}});ok(forgotten.status===200&&!forgotten.data.developmentToken,'recuperación con proveedor no expone el token en la respuesta');
  const sentMail=mailRequests[0],resetUrl=sentMail?.body?.content?.find(item=>item.type==='text/plain')?.value?.match(/https?:\/\/[^\s]+/)?.[0],resetToken=new URL(resetUrl).searchParams.get('token');ok(sentMail?.url==='/v3/mail/send'&&sentMail.authorization==='Bearer SG.test-only-not-a-secret'&&sentMail.body.personalizations[0].to[0].email==='cliente@test.local'&&resetToken,'recuperación entrega por SendGrid un enlace temporal al correo correcto');
  const unknownForgotten=await api('/api/auth/forgot-password',{method:'POST',body:{email:'no-existe@test.local'}});ok(unknownForgotten.status===200&&mailRequests.length===1,'recuperación no revela cuentas inexistentes ni intenta enviarles correo');
  const reset=await api('/api/auth/reset-password',{method:'POST',body:{token:resetToken,password:'Cliente-Nueva-2026'}});ok(reset.status===200,'enlace válido cambia la contraseña');
  const oldSession=await api('/api/orders/my',{token:previousCustomerToken}),reusedReset=await api('/api/auth/reset-password',{method:'POST',body:{token:resetToken,password:'Otra-Clave-2026'}});ok(oldSession.status===401&&reusedReset.status===400,'cambio invalida sesiones anteriores y el enlace sólo se usa una vez');
  customer.data.token=await login('cliente@test.local','Cliente-Nueva-2026','customer');
  const customerTokenBeforeChange=customer.data.token,ownPassword=await api('/api/auth/password',{token:customer.data.token,method:'PATCH',body:{currentPassword:'Cliente-Nueva-2026',newPassword:'Cliente-Final-2026'}});ok(ownPassword.status===200&&ownPassword.data.token,'cliente cambia su propia contraseña y recibe una sesión nueva');
  const previousOwnSession=await api('/api/orders/my',{token:customerTokenBeforeChange});ok(previousOwnSession.status===401,'cambio propio cierra las demás sesiones');customer.data.token=ownPassword.data.token;
  const aiStatus=await api('/api/ai/status',{token:admin});ok(aiStatus.status===200&&aiStatus.data.enabled===false,'asistente informa cuando falta configuración');
  const aiUnavailable=await api('/api/ai/chat',{token:admin,method:'POST',body:{message:'Resume la operación'}});ok(aiUnavailable.status===503,'asistente falla de forma segura sin clave');
  const pushKey=await api('/api/push/public-key',{token:admin});ok(pushKey.status===200&&typeof pushKey.data.publicKey==='string'&&pushKey.data.publicKey.length>40,'servidor prepara notificaciones móviles cifradas');
  const invalidPush=await api('/api/push/subscribe',{token:admin,method:'POST',body:{subscription:{endpoint:'http://inseguro.local',keys:{p256dh:'corta',auth:'corta'}}}});ok(invalidPush.status===400,'servidor rechaza suscripciones push inseguras o incompletas');
  for(const user of [{name:'Restaurante Prueba',email:'rest@test.local',phone:'3411',password:'Restaurante-12',role:'restaurant'},{name:'Repartidor Uno',email:'rep1@test.local',password:'Repartidor-uno-12',role:'delivery'},{name:'Repartidor Dos',email:'rep2@test.local',password:'Repartidor-dos-12',role:'delivery'}]){const c=await api('/api/admin/users',{token:admin,method:'POST',body:user});ok(c.status===201,'administrador crea '+user.role);const a=await api('/api/admin/users/'+c.data.id+'/status',{token:admin,method:'PATCH',body:{status:'approved'}});ok(a.status===200,'administrador aprueba '+user.email)}
  const restaurant=await login('rest@test.local','Restaurante-12','restaurant'),d1=await login('rep1@test.local','Repartidor-uno-12','delivery'),d2=await login('rep2@test.local','Repartidor-dos-12','delivery');
  const customerAdminDenied=await api('/api/admin/scheduled-orders',{token:customer.data.token}),deliveryRestaurantDenied=await api('/api/restaurant/me',{token:d1});ok(customerAdminDenied.status===403&&deliveryRestaurantDenied.status===403,'roles no pueden consultar paneles ajenos');
  const savedAddress=await api('/api/customer/addresses',{token:customer.data.token,method:'POST',body:{label:'Casa',address:'Calle de prueba 123',reference:'Portón naranja',latitude:19.89,longitude:-103.60,isDefault:true}});ok(savedAddress.status===201&&savedAddress.data.is_default===1,'cliente guarda domicilio con ubicación exacta');
  const customerAddresses=await api('/api/customer/addresses',{token:customer.data.token});ok(customerAddresses.status===200&&customerAddresses.data.length===1&&customerAddresses.data[0].reference==='Portón naranja','cliente consulta únicamente sus direcciones');
  const courierAddresses=await api('/api/customer/addresses',{token:d1});ok(courierAddresses.status===403,'repartidor no puede consultar direcciones guardadas');
  const employeeCreated=await api('/api/restaurant/employees',{token:restaurant,method:'POST',body:{name:'Empleado Pedidos',email:'empleado@test.local',phone:'3412',password:'Empleado-Seguro-12',canManageOrders:true,canManageProducts:false,canViewFinance:false}});ok(employeeCreated.status===201,'dueño crea acceso individual para empleado');
  const employee=await login('empleado@test.local','Empleado-Seguro-12','restaurant');
  const employeePanel=await api('/api/restaurant/me',{token:employee});ok(employeePanel.status===200&&employeePanel.data.access?.isOwner===false&&employeePanel.data.access?.canManageOrders===true,'empleado entra al negocio con permisos propios');
  const employeeFinance=await api('/api/restaurant/settlement',{token:employee});ok(employeeFinance.status===403,'empleado sin permiso no puede ver cortes');
  const employeeProduct=await api('/api/restaurant/products',{token:employee,method:'POST',body:{name:'No autorizado',price:20}});ok(employeeProduct.status===403,'empleado sin permiso no puede modificar productos');
  const employeePos=await api('/api/restaurant/pos',{token:employee});ok(employeePos.status===403,'empleado sin permiso no puede usar el punto de venta');
  await api('/api/restaurant/location',{token:restaurant,method:'PUT',body:{latitude:19.8826,longitude:-103.5998}});
  const sampleImage='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
  const optimizedImage=await api('/api/restaurant/uploads',{token:restaurant,method:'POST',body:{dataUrl:sampleImage}});ok(optimizedImage.status===201&&optimizedImage.data.url.endsWith('.webp')&&optimizedImage.data.storedBytes>0,'fotografía se valida y optimiza automáticamente');
  const storedImage=await fetch(base+optimizedImage.data.url);ok(storedImage.status===200&&storedImage.headers.get('content-type')==='image/webp','servidor entrega la fotografía optimizada');
  const storage=await api('/api/admin/storage',{token:admin});ok(storage.status===200&&storage.data.capacityBytes===1073741824&&storage.data.uploadsBytes>0,'administrador consulta capacidad y uso del disco');
  const product=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Pedido controlado',description:'Prueba',price:100,image:''}});ok(product.status===201,'producto controlado creado');
  const drink=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Agua fresca',description:'Bebida de prueba',price:25,image:'',category:'Bebidas'}});ok(drink.status===201&&drink.data.category==='Bebidas','restaurante clasifica bebidas en su menú');
  const alcohol=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Bebida para adultos',description:'Prueba protegida',price:45,image:'',category:'Bebidas alcohólicas'}});ok(alcohol.status===201&&alcohol.data.category==='Bebidas alcohólicas','restaurante clasifica bebidas alcohólicas');
  const cashOpened=await api('/api/restaurant/cash/open',{token:restaurant,method:'POST',body:{openingAmount:500,note:'Inicio de turno'}});ok(cashOpened.status===201&&cashOpened.data.currentExpected===500,'restaurante abre caja con fondo inicial');
  const cashMovement=await api('/api/restaurant/cash/movements',{token:restaurant,method:'POST',body:{type:'withdrawal',amount:50,reason:'Compra de insumos'}});ok(cashMovement.status===201&&cashMovement.data.currentExpected===450,'caja registra retiros con motivo');
  const posRequest=crypto.randomUUID(),posDenied=await api('/api/restaurant/pos/sales',{token:restaurant,method:'POST',body:{items:[{productId:alcohol.data.id,quantity:2}],paymentMethod:'Efectivo',clientRequestId:posRequest,ageConfirmed:false}});ok(posDenied.status===403,'punto de venta exige verificación de mayoría de edad');
  const posCardRejected=await api('/api/restaurant/pos/sales',{token:restaurant,method:'POST',body:{items:[{productId:alcohol.data.id,quantity:1}],paymentMethod:'Tarjeta',clientRequestId:crypto.randomUUID(),ageConfirmed:true,cardNumber:'NO-GUARDAR',cvv:'XXX'}});ok(posCardRejected.status===400,'punto de venta rechaza datos sensibles de tarjeta');
  const posSale=await api('/api/restaurant/pos/sales',{token:restaurant,method:'POST',body:{items:[{productId:alcohol.data.id,quantity:2}],paymentMethod:'Efectivo',clientRequestId:posRequest,ageConfirmed:true}});ok(posSale.status===201&&posSale.data.total===90&&posSale.data.receiptNumber.startsWith('POS-'),'punto de venta registra venta local con folio independiente');
  const posRepeated=await api('/api/restaurant/pos/sales',{token:restaurant,method:'POST',body:{items:[{productId:alcohol.data.id,quantity:2}],paymentMethod:'Efectivo',clientRequestId:posRequest,ageConfirmed:true}});ok(posRepeated.status===200&&posRepeated.data.repeated,'punto de venta evita cobro duplicado');
  let posPanel=await api('/api/restaurant/pos',{token:restaurant});ok(posPanel.data.today.total===90&&posPanel.data.sales[0].items[0].category==='Bebidas alcohólicas','venta local aparece en resumen sin pedido de reparto');
  const cashStatus=await api('/api/restaurant/cash',{token:restaurant});ok(cashStatus.status===200&&cashStatus.data.open.currentExpected===540,'caja suma automáticamente ventas en efectivo');
  const cashClosed=await api('/api/restaurant/cash/close',{token:restaurant,method:'POST',body:{countedAmount:535,note:'Cierre controlado'}});ok(cashClosed.status===200&&cashClosed.data.difference_amount===-5&&cashClosed.data.status==='closed','cierre compara efectivo contado contra esperado');
  const analytics=await api('/api/restaurant/analytics?days=7',{token:restaurant});ok(analytics.status===200&&analytics.data.pos.total===90&&analytics.data.cash.net_difference===-5&&analytics.data.topProducts.some(item=>item.product_name==='Bebida para adultos'),'estadísticas integran mostrador, productos y diferencias de caja');
  const employeeAnalytics=await api('/api/restaurant/analytics?days=7',{token:employee});ok(employeeAnalytics.status===403,'estadísticas respetan permisos financieros');
  const posVoid=await api('/api/restaurant/pos/sales/'+posSale.data.id+'/void',{token:restaurant,method:'POST',body:{reason:'Cancelación de prueba'}});posPanel=await api('/api/restaurant/pos',{token:restaurant});ok(posVoid.status===200&&posPanel.data.today.total===0&&posPanel.data.today.voided===1,'venta local puede anularse con motivo y auditoría');
  const me=await api('/api/restaurant/me',{token:restaurant}),restaurantId=me.data.id;
  const visibility=await api('/api/admin/restaurants/'+restaurantId+'/visibility',{token:admin,method:'PATCH',body:{category:'Comida mexicana',priority:80,featured:true}});ok(visibility.status===200&&visibility.data.featured,'administrador destaca y prioriza restaurante');
  const closed=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'closed',prepMinutes:30,specialHours:'Cierre de prueba'}});ok(closed.status===200,'restaurante puede cerrar pedidos');
  const rejectedClosed=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(rejectedClosed.status===409,'un restaurante cerrado no recibe pedidos');
  const saturated=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'saturated',prepMinutes:30,specialHours:'Alta demanda'}});ok(saturated.status===200&&saturated.data.estimatedPrepMinutes===50,'modo saturado aumenta veinte minutos');
  const publicRestaurants=await api('/api/restaurants');ok(publicRestaurants.data[0]?.id===restaurantId&&publicRestaurants.data[0]?.category==='Comida mexicana'&&publicRestaurants.data[0]?.featured===1&&publicRestaurants.data[0]?.operational_status==='saturated','prioridad, categoría y disponibilidad aparecen en directorio');
  const publicMenu=await api('/api/restaurants/'+restaurantId+'/menu');ok(publicMenu.data.products.some(p=>p.category==='Bebidas')&&publicMenu.data.products.some(p=>p.category==='Bebidas alcohólicas'),'clientes reciben las nuevas categorías del menú');
  const orderBase=()=>({restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()});
  const cardRejected=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),cardNumber:'NO-GUARDAR',securityCode:'XXX'}});ok(cardRejected.status===400,'pedidos rechazan datos sensibles de tarjeta');
  const auditDenied=await api('/api/admin/audit',{token:customer.data.token}),auditAllowed=await api('/api/admin/audit?limit=25',{token:admin});ok(auditDenied.status===403&&auditAllowed.status===200&&auditAllowed.data.some(entry=>entry.action==='password_reset_completed'),'auditoría reciente sólo está disponible para administración');
  for(const test of [
    {name:'fecha programada inválida',body:{orderTiming:'scheduled',scheduledFor:'no-es-fecha'}},
    {name:'fecha programada pasada',body:{orderTiming:'scheduled',scheduledFor:new Date(Date.now()-60*60*1000).toISOString()}},
    {name:'menos de 45 minutos de anticipación',body:{orderTiming:'scheduled',scheduledFor:new Date(Date.now()+44*60*1000).toISOString()}},
    {name:'más de siete días de anticipación',body:{orderTiming:'scheduled',scheduledFor:new Date(Date.now()+7*24*60*60*1000+60*1000).toISOString()}}
  ]){const rejected=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),...test.body}});ok(rejected.status===400,'servidor rechaza '+test.name)}
  const sayulaTarget=new Date(Date.now()+46*60*1000),sayulaLocal=new Date(sayulaTarget.getTime()-6*60*60*1000).toISOString().slice(0,19)+'-06:00',sayulaScheduled=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),orderTiming:'scheduled',scheduledFor:sayulaLocal}});ok(sayulaScheduled.status===201&&Math.abs(new Date(sayulaScheduled.data.scheduledFor)-sayulaTarget)<1000,'servidor normaliza correctamente una hora explícita de Sayula');
  const longPrep=await api('/api/restaurant/availability',{token:restaurant,method:'PUT',body:{status:'saturated',prepMinutes:100,specialHours:'Preparación larga de prueba'}});ok(longPrep.status===200&&longPrep.data.estimatedPrepMinutes===120,'tiempo operativo incluye preparación configurada y saturación');
  const requestedDate=new Date(Date.now()+100*60*1000),scheduled=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),orderTiming:'scheduled',scheduledFor:requestedDate.toISOString()}});ok(scheduled.status===201&&scheduled.data.orderTiming==='scheduled','pedido programado válido creado');ok(Math.abs(new Date(scheduled.data.scheduledFor).getTime()-requestedDate.getTime())<1000,'servidor guarda la fecha programada normalizada');
  const acceptedScheduled=await api('/api/restaurant/orders/'+scheduled.data.orderId,{token:restaurant,method:'PATCH',body:{status:'accepted'}});ok(acceptedScheduled.status===200,'restaurante acepta el pedido programado');const preparingScheduled=await api('/api/restaurant/orders/'+scheduled.data.orderId,{token:restaurant,method:'PATCH',body:{status:'preparing'}});ok(preparingScheduled.status===200,'preparación se habilita según el tiempo configurado');const earlyReady=await api('/api/restaurant/orders/'+scheduled.data.orderId,{token:restaurant,method:'PATCH',body:{status:'ready'}});ok(earlyReady.status===409,'pedido programado no puede marcarse listo demasiado pronto');
  const scheduledNotices=await api('/api/notifications',{token:restaurant});ok(scheduledNotices.data.notifications.some(n=>n.order_id===scheduled.data.orderId&&n.type==='scheduled_prep_reminder'),'restaurante recibe recordatorio al entrar en la ventana de preparación');
  const scheduledAdmin=await api('/api/admin/scheduled-orders',{token:admin});ok(scheduledAdmin.status===200&&scheduledAdmin.data.summary.upcoming===2&&scheduledAdmin.data.orders.every(order=>order.prep_start_at),'administrador consulta próximos y hora de preparación');
  const fixtureDb=new Database(dbFile);fixtureDb.prepare("UPDATE orders SET status='ready' WHERE id=?").run(scheduled.data.orderId);fixtureDb.close();
  const alcoholDeliveryDenied=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:alcohol.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID(),ageConfirmed:false}});ok(alcoholDeliveryDenied.status===403,'pedido a domicilio con alcohol exige confirmación de mayoría de edad');
  const cancelledOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Pedido que será cancelado',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});const cancelled=await api('/api/restaurant/orders/'+cancelledOrder.data.orderId,{token:restaurant,method:'PATCH',body:{status:'cancelled'}});ok(cancelled.status===200,'restaurante cancela un pedido antes de prepararlo');
  const unansweredOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{...orderBase(),address:'Pedido sin respuesta de prueba'}}),noticeDb=new Database(dbFile);noticeDb.prepare("UPDATE orders SET created_at=datetime('now','-20 minutes') WHERE id=?").run(unansweredOrder.data.orderId);noticeDb.close();await wait(300);const unansweredCustomer=await api('/api/notifications',{token:customer.data.token}),unansweredRestaurant=await api('/api/notifications',{token:restaurant}),unansweredAdmin=await api('/api/notifications',{token:admin});ok([unansweredCustomer,unansweredRestaurant,unansweredAdmin].every(result=>result.data.notifications.some(n=>n.order_id===unansweredOrder.data.orderId&&n.type==='order_unanswered')),'cliente, restaurante y administrador reciben alerta de pedido sin respuesta');
  const limited=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Última pieza',price:55,stockEnabled:true,stockQuantity:1,lowStockThreshold:1}}),limitedBody=()=>({restaurantId,items:[{productId:limited.data.id,quantity:1}],address:'Prueba de inventario',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}),stockRace=await Promise.all([api('/api/orders',{token:customer.data.token,method:'POST',body:limitedBody()}),api('/api/orders',{token:customer.data.token,method:'POST',body:limitedBody()})]);ok(stockRace.filter(result=>result.status===201).length===1&&stockRace.filter(result=>result.status===409).length===1,'inventario simultáneo permite vender únicamente la existencia disponible');
  const configurable=await api('/api/restaurant/products',{token:restaurant,method:'POST',body:{name:'Producto configurable',price:80,variants:[{name:'Grande',priceDelta:20}],addons:[{name:'Queso',priceDelta:10}]}}),configuredOrder=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:configurable.data.id,quantity:1,variant:'Grande',addons:['Queso']}],address:'Prueba de repetición',paymentMethod:'Efectivo',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});await api('/api/restaurant/products/'+configurable.data.id,{token:restaurant,method:'PUT',body:{name:'Producto configurable',description:'Actualizado',image:'',category:'Comida',price:90,stockEnabled:false,variants:[{name:'Grande',priceDelta:30}],addons:[{name:'Salsa',priceDelta:5}]}});const changedRepeat=await api('/api/orders/'+configuredOrder.data.orderId+'/repeat',{token:customer.data.token});ok(changedRepeat.status===200&&changedRepeat.data.items[0].price===120&&changedRepeat.data.items[0].addons.length===0&&changedRepeat.data.warnings.some(message=>message.includes('complementos')),'repetición usa precio actual y advierte complementos retirados');await api('/api/restaurant/products/'+configurable.data.id,{token:restaurant,method:'PATCH',body:{available:false}});const unavailableRepeat=await api('/api/orders/'+configuredOrder.data.orderId+'/repeat',{token:customer.data.token});ok(unavailableRepeat.status===409,'repetición rechaza un pedido cuyos productos quedaron agotados');
  const orders=[];
  for(const paymentMethod of ['Efectivo','Transferencia','Tarjeta al recibir']){const created=await api('/api/orders',{token:customer.data.token,method:'POST',body:{restaurantId,items:[{productId:product.data.id,quantity:1}],address:'Domicilio controlado',paymentMethod,orderTiming:'immediate',deliveryLatitude:19.89,deliveryLongitude:-103.60,clientRequestId:crypto.randomUUID()}});ok(created.status===201&&created.data.orderTiming==='immediate'&&created.data.scheduledFor===null,'pedido inmediato creado con '+paymentMethod);ok(created.data.paymentStatus===(paymentMethod==='Transferencia'?'awaiting_confirmation':'pay_on_delivery'),'estado de pago correcto para '+paymentMethod);orders.push({id:created.data.orderId,paymentMethod});if(paymentMethod==='Transferencia'){const paid=await api('/api/restaurant/orders/'+created.data.orderId+'/payment',{token:restaurant,method:'PATCH',body:{}});ok(paid.status===200&&paid.data.paymentStatus==='confirmed','transferencia conciliada manualmente')}for(const status of ['accepted','preparing','ready']){const actor=status==='accepted'&&paymentMethod==='Efectivo'?employee:restaurant;const moved=await api('/api/restaurant/orders/'+created.data.orderId,{token:actor,method:'PATCH',body:{status}});ok(moved.status===200,'pedido '+created.data.orderId+' cambia a '+status)}}
  const backwards=await api('/api/restaurant/orders/'+orders[0].id,{token:restaurant,method:'PATCH',body:{status:'accepted'}}),stillReady=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token});ok(backwards.status===400&&stillReady.data.status==='ready','un pedido nunca puede retroceder de estado');
  await Promise.all([api('/api/delivery/location',{token:d1,method:'PUT',body:{latitude:19.88,longitude:-103.60,accuracy:5}}),api('/api/delivery/location',{token:d2,method:'PUT',body:{latitude:19.881,longitude:-103.60,accuracy:5}})]);
  const earlyAvailable=await api('/api/delivery/orders/available',{token:d1});ok(!earlyAvailable.data.orders.some(order=>order.id===scheduled.data.orderId),'pedido programado no se ofrece al repartidor con demasiada anticipación');
  const earlyAccept=await api('/api/delivery/orders/'+scheduled.data.orderId+'/accept',{token:d1,method:'POST'});ok(earlyAccept.status===409,'API bloquea aceptación anticipada del pedido programado');
  const customerNotices=await api('/api/notifications',{token:customer.data.token});ok(customerNotices.status===200&&customerNotices.data.notifications.some(n=>n.type==='order_ready'),'cliente recibe avisos persistentes del avance');
  const employeeNotices=await api('/api/notifications',{token:employee});ok(employeeNotices.status===200&&employeeNotices.data.notifications.some(n=>n.type==='order_received'),'empleado autorizado recibe aviso de pedido nuevo');
  const readNotices=await api('/api/notifications/read',{token:customer.data.token,method:'PATCH',body:{}});const afterRead=await api('/api/notifications',{token:customer.data.token});ok(readNotices.status===200&&afterRead.data.unread===0,'usuario puede marcar sus avisos como leídos');
  const race=await Promise.all([api('/api/delivery/orders/'+orders[0].id+'/accept',{token:d1,method:'POST'}),api('/api/delivery/orders/'+orders[0].id+'/accept',{token:d2,method:'POST'})]);ok(race.filter(r=>r.status===200).length===1&&race.filter(r=>r.status===409).length===1,'sólo un repartidor gana la aceptación concurrente');
  const winner=race[0].status===200?d1:d2,started=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:'delivering'}});ok(started.status===200,'entrega avanza a delivering');const shared=await api('/api/delivery/orders/'+orders[0].id+'/location',{token:winner,method:'PATCH',body:{latitude:19.885,longitude:-103.601,accuracy:5}});ok(shared.status===200,'repartidor comparte ubicación durante entrega');const deliveryTracking=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token}),badPin=deliveryTracking.data.delivery_pin==='0000'?'0001':'0000',missingPin=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:'delivered'}}),wrongPin=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:'delivered',deliveryPin:badPin}}),beforePin=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token});ok(missingPin.status===403&&wrongPin.status===403&&beforePin.data.status==='delivering','PIN correcto es obligatorio y los intentos fallidos no cierran el pedido');const delivered=await api('/api/delivery/orders/'+orders[0].id,{token:winner,method:'PATCH',body:{status:'delivered',deliveryPin:beforePin.data.delivery_pin}});ok(delivered.status===200,'entrega avanza a delivered con el PIN correcto');
  for(let i=1;i<orders.length;i++){const courier=i%2?d1:d2;const accepted=await api('/api/delivery/orders/'+orders[i].id+'/accept',{token:courier,method:'POST'});ok(accepted.status===200,'repartidor acepta pedido con '+orders[i].paymentMethod);for(const state of ['delivering','delivered']){const tracking=await api('/api/orders/'+orders[i].id+'/tracking',{token:customer.data.token});const moved=await api('/api/delivery/orders/'+orders[i].id,{token:courier,method:'PATCH',body:{status:state,deliveryPin:tracking.data.delivery_pin}});ok(moved.status===200,'flujo '+orders[i].paymentMethod+' termina en '+state)}}
  const closedTracking=await api('/api/orders/'+orders[0].id+'/tracking',{token:customer.data.token});ok(closedTracking.status===200&&closedTracking.data.latitude===null&&closedTracking.data.longitude===null&&closedTracking.data.delivery_phone===null,'seguimiento oculta ubicación y teléfono después de entregar');
  const finalCustomerNotices=await api('/api/notifications',{token:customer.data.token}),customerTypes=new Set(finalCustomerNotices.data.notifications.filter(n=>n.order_id===orders[0].id).map(n=>n.type));for(const type of ['order_accepted','order_preparing','order_ready','order_assigned','order_delivering','order_delivered'])ok(customerTypes.has(type),'cliente recibe aviso '+type);
  const finalRestaurantNotices=await api('/api/notifications',{token:restaurant}),restaurantTypes=new Set(finalRestaurantNotices.data.notifications.filter(n=>n.order_id===orders[0].id).map(n=>n.type));for(const type of ['order_assigned','order_delivering','order_delivered'])ok(restaurantTypes.has(type),'restaurante recibe aviso '+type);
  const repeatOrder=await api('/api/orders/'+orders[0].id+'/repeat',{token:customer.data.token});ok(repeatOrder.status===200&&repeatOrder.data.items.length>0&&repeatOrder.data.items[0].restaurantId===restaurantId,'cliente puede repetir un pedido con precios y disponibilidad actuales');
  const closedRestaurantView=await api('/api/restaurant/me',{token:restaurant});const closedOrder=closedRestaurantView.data.orders.find(item=>item.id===orders[0].id);ok(closedOrder?.customer_phone===null&&closedOrder?.delivery_latitude===null&&closedOrder?.address==='Datos ocultos al cerrar el pedido','restaurante deja de ver datos personales al cerrar el pedido');
  const review=await api('/api/orders/'+orders[0].id+'/review',{token:customer.data.token,method:'POST',body:{restaurantRating:5,deliveryRating:4,tipAmount:20,comment:'Entrega controlada'}});ok(review.status===201&&review.data.tipAmount===20&&review.data.tipMethod==='cash','cliente califica y registra propina en efectivo');
  const duplicateReview=await api('/api/orders/'+orders[0].id+'/review',{token:customer.data.token,method:'POST',body:{restaurantRating:5,tipAmount:0}});ok(duplicateReview.status===409,'un pedido no puede calificarse dos veces');
  const courierHistory=await api('/api/delivery/orders/my',{token:winner});ok(courierHistory.data.find(item=>item.id===orders[0].id)?.tip_amount===20,'repartidor ve la propina registrada');
  const ratedRestaurants=await api('/api/restaurants');ok(ratedRestaurants.data.find(item=>item.id===restaurantId)?.rating===5,'calificación actualiza reputación del restaurante');
  const feedbackBody={category:'error',rating:3,answers:['Sí','Sí','No','Avisos más claros'],comment:'La pantalla del pedido tardó en actualizar',orderId:orders[0].id,anonymous:true,contactAllowed:true};
  const feedback=await api('/api/feedback',{token:customer.data.token,method:'POST',body:feedbackBody});ok(feedback.status===201&&/^[a-f0-9]{24}$/.test(feedback.data.trackingCode),'cliente envía opinión anónima y recibe folio privado');
  const feedbackStatus=await api('/api/feedback/status/'+feedback.data.trackingCode);ok(feedbackStatus.status===200&&feedbackStatus.data.status==='received','folio permite consultar estado de opinión');
  const repeated=await api('/api/feedback',{token:customer.data.token,method:'POST',body:{...feedbackBody,orderId:orders[1].id}});ok(repeated.status===201,'se acepta un segundo reporte del mismo problema');
  const adminFeedback=await api('/api/admin/feedback',{token:admin});const reported=adminFeedback.data.find(item=>item.id===feedback.data.id);ok(adminFeedback.status===200&&reported?.frequency===2&&reported.user_id===null&&reported.contact_email===null,'panel agrupa reportes repetidos y protege el anonimato');
  const feedbackUpdate=await api('/api/admin/feedback/'+feedback.data.id,{token:admin,method:'PATCH',body:{status:'reviewing',severity:'high',adminNotes:'Revisar actualización del seguimiento'}});ok(feedbackUpdate.status===200&&feedbackUpdate.data.severity==='high','administrador clasifica gravedad y avance');
  const updatedFeedbackStatus=await api('/api/feedback/status/'+feedback.data.trackingCode);ok(updatedFeedbackStatus.data.status==='reviewing'&&updatedFeedbackStatus.data.severity==='high','usuario consulta el avance actualizado');
  const issue=await api('/api/order-issues',{token:customer.data.token,method:'POST',body:{orderId:orders[0].id,issueType:'missing_product',description:'Faltó una bebida en la prueba'}});ok(issue.status===201,'cliente reporta problema relacionado con su pedido');
  const issuesAdmin=await api('/api/admin/order-issues',{token:admin});ok(issuesAdmin.data.some(item=>item.id===issue.data.id),'administrador ve el problema reportado');
  const issueUpdated=await api('/api/admin/order-issues/'+issue.data.id,{token:admin,method:'PATCH',body:{status:'resolved',adminNotes:'Resuelto en prueba'}});ok(issueUpdated.status===200,'administrador resuelve el problema');
  const demo=await api('/api/admin/demo/create',{token:admin,method:'POST',body:{}});ok(demo.status===201&&demo.data.status==='received','administrador crea pedido de demostración aislado');
  for(const expected of ['accepted','preparing','ready','assigned','delivering','delivered']){const advanced=await api('/api/admin/demo/'+demo.data.orderId+'/advance',{token:admin,method:'POST',body:{}});ok(advanced.status===200&&advanced.data.status===expected,'demostración avanza a '+expected)}
  const resetDemo=await api('/api/admin/demo',{token:admin,method:'DELETE'});ok(resetDemo.status===200&&resetDemo.data.removed===1,'reinicio elimina únicamente el pedido de demostración');
  const subscriptions=await api('/api/admin/subscriptions',{token:admin});const subscription=subscriptions.data.find(s=>s.restaurant_id===restaurantId);ok(subscription?.registration_fee===50&&subscription?.first_month_fee===100&&subscription?.initial_payment_total===150&&subscription?.promotion_monthly_fee===100&&subscription?.regular_monthly_fee===200,'inscripción y primera mensualidad quedan desglosadas');
  const registration=await api('/api/admin/subscriptions/'+restaurantId+'/payment',{token:admin,method:'PATCH',body:{acceptedTerms:true}});ok(registration.status===200&&registration.data.firstMonthIncluded,'inscripción confirmada incluye primera mensualidad');
  let settlement=await api('/api/restaurant/settlement',{token:restaurant});ok(settlement.status===200&&settlement.data.days[0]?.orders_count===3&&settlement.data.days[0]?.sales===300&&settlement.data.days[0]?.cancellations===1&&settlement.data.days[0]?.reversed_amount===135,'corte excluye ventas canceladas y conserva su reversión');
  const pendingSettlements=await api('/api/admin/settlements',{token:admin});const pendingCut=pendingSettlements.data.pending.find(c=>c.restaurant_id===restaurantId);ok(pendingCut?.amount===300,'administrador ve únicamente el saldo válido pendiente');
  const proof='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
  const paidCut=await api('/api/admin/settlements',{token:admin,method:'POST',body:{restaurantId,periodDate:pendingCut.period_date,reference:'TRX-PRUEBA-001',proofDataUrl:proof}});ok(paidCut.status===201&&paidCut.data.amount===300,'administrador registra fecha, referencia y comprobante del corte');
  settlement=await api('/api/restaurant/settlement',{token:restaurant});ok(settlement.data.days[0]?.pending_due===0&&settlement.data.days[0]?.paid_due===300&&settlement.data.batches[0]?.reference==='TRX-PRUEBA-001','restaurante consulta corte pagado e historial');
  const proofResponse=await fetch(base+'/api/settlements/'+paidCut.data.batchId+'/proof',{headers:{Authorization:'Bearer '+restaurant}});ok(proofResponse.status===200&&String(proofResponse.headers.get('content-type')).startsWith('image/'),'comprobante privado sólo se obtiene con sesión autorizada');
  const duplicateCut=await api('/api/admin/settlements',{token:admin,method:'POST',body:{restaurantId,periodDate:pendingCut.period_date,reference:'DUPLICADO'}});ok(duplicateCut.status===409,'un corte pagado no puede conciliarse dos veces');
  const history=await api('/api/orders/my',{token:customer.data.token});for(const order of orders){const saved=history.data.find(item=>item.id===order.id);ok(saved?.status==='delivered','pedido '+order.paymentMethod+' quedó entregado');ok(saved?.payment_status===(order.paymentMethod==='Transferencia'?'confirmed':'paid'),'pago final correcto para '+order.paymentMethod)}
  const savedScheduled=history.data.find(item=>item.id===scheduled.data.orderId);ok(savedScheduled?.order_timing==='scheduled'&&savedScheduled?.scheduled_for,'cliente recibe la fecha del pedido programado');const restaurantScheduled=(await api('/api/restaurant/me',{token:restaurant})).data.orders.find(item=>item.id===scheduled.data.orderId);ok(restaurantScheduled?.order_timing==='scheduled'&&restaurantScheduled?.scheduled_for,'restaurante recibe la fecha del pedido programado');
  console.log('\nTodas las pruebas controladas terminaron correctamente.');
}
run().catch(error=>{console.error('PRUEBA FALLIDA:',error.message);process.exitCode=1}).finally(()=>{child.kill();mailServer.close();setTimeout(()=>{for(const suffix of ['', '-wal','-shm'])try{fs.unlinkSync(dbFile+suffix)}catch(e){}},300)});
